(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  root.IterionMods=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const registry=new Map();
  const canonicalDominoes=Object.freeze(Array.from({length:7},(_,a)=>Array.from({length:7-a},(_,offset)=>Object.freeze({a,b:a+offset,key:`${a}|${a+offset}`}))).flat());
  function register(mod){if(!mod?.id)throw new Error('Mod requires id');const displayName=mod.displayName||mod.name||mod.id,shortDescription=mod.shortDescription||mod.description||'',rulesDescription=mod.rulesDescription||mod.description||shortDescription;const normalized={...mod,displayName,shortDescription,rulesDescription,name:mod.name||displayName,description:mod.description||shortDescription};registry.set(mod.id,Object.freeze(normalized));return normalized}
  function get(id){return registry.get(id)||null}
  function all(){return [...registry.values()]}
  function collection(){const assigned=new Map();for(const mod of registry.values()){const tile=mod.collectionTile;if(!Array.isArray(tile)||tile.length!==2)continue;const a=Math.min(Number(tile[0]),Number(tile[1])),b=Math.max(Number(tile[0]),Number(tile[1])),key=`${a}|${b}`;if(assigned.has(key))throw new Error(`Duplicate Mod collection domino ${key}`);assigned.set(key,mod)}return canonicalDominoes.map(tile=>Object.freeze({...tile,mod:assigned.get(tile.key)||null}))}
  register({id:'move',displayName:'+1 MOVE',name:'+1 MOVE',kind:'consumable',cost:3,shortDescription:'Store one extra move.',rulesDescription:'Store one extra move. Spend it whenever you need one additional placement in the current round.',description:'Store one extra move. Use it whenever you need one more placement in the current round.'});
  register({id:'reroll',displayName:'REROLL',name:'REROLL',kind:'consumable',cost:3,shortDescription:'Store one full-hand reroll.',rulesDescription:'Store one full-hand reroll. It remains available until you choose to spend it, replacing the current hand with a new draw.',description:'Store one full-hand reroll. It remains available until you choose to spend it.'});
  register({id:'undo',displayName:'UNDO',name:'UNDO',kind:'consumable',cost:4,shortDescription:'Store one undo.',rulesDescription:'Store one undo. Revert the last placement and its gameplay result. Purchases made after that placement remain spent and remain owned.',description:'Store one undo. Revert the last placement; purchases made afterwards are not refunded.'});
  register({id:'double-double',category:'signal',displayName:'DOUBLE DOUBLE',name:'DOUBLE DOUBLE',kind:'market-tile-mod',market:true,target:'double',marketCostKey:'MARKET_DOUBLE_DOUBLE_COST',collectionTile:[2,2],collectionCode:'DD',collectionDefaultUnlocked:true,shortDescription:'First activation: repeat.',rulesDescription:'Choose one eligible non-zero physical double already placed in the machine. Its first activation each Move repeats its scoring operation once; later passes in the same Move use the normal double operation.',description:'Repeat this double once on its first activation each Move.'});
  register({id:'long-run',category:'economy',displayName:'LONG CHAIN',name:'LONG CHAIN',kind:'market-machine-mod',market:true,target:'machine',marketCostKey:'MARKET_LONG_RUN_COST',collectionTile:[6,6],collectionCode:'LC',collectionDefaultUnlocked:true,shortDescription:'10+ tiles: every ★ pays.',rulesDescription:'When the chosen route traverses at least 10 unique physical tiles in one Move, every starred physical tile activated on that route pays its tier once. In Endless, this full payout is limited to 7 qualifying Moves; afterwards the normal highest-star-wins rule returns.',description:'At 10+ unique routed tiles, all activated stars pay once. Endless allows 7 full payouts.'});
  register({id:'zero-port',category:'mutation',displayName:'ZERO PORT',name:'ZERO PORT',kind:'market-tile-mod',market:true,target:'zero-port',marketCostKey:'MARKET_ZERO_PORT_COST',collectionTile:[0,0],collectionCode:'ZP',collectionDefaultUnlocked:true,shortDescription:'Pair 2 zeros. Teleport.',rulesDescription:'Install Zero Port on zero tiles. With two installed, a signal reaching a Zero Port teleports to the paired tile instead of rebounding. If the receiving tile is [0|0], the signal duplicates through both physical ends. Buying Zero Port again with a complete pair relocates one endpoint.',description:'Pair two zero tiles into a teleport link; a third purchase relocates one endpoint.'});
  register({id:'parity-exchange',category:'mutation',displayName:'PARITY EXCHANGE',name:'PARITY EXCHANGE',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_PARITY_EXCHANGE_COST',collectionTile:[1,2],collectionCode:'PX',collectionDefaultUnlocked:true,shortDescription:'Odd +. Even ×.',rulesDescription:'Choose one placed physical tile. On that tile only, odd non-zero values add and even non-zero values multiply. Printed values, matching and routing do not change.',description:'Odd values add and even values multiply on this tile.'});
  register({id:'corner',category:'topology',topologyRule:'corner',displayName:'CORNER',name:'CORNER',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_CORNER_COST',collectionTile:[2,3],collectionCode:'CR',collectionDefaultUnlocked:true,shortDescription:'Corner: ×3.',rulesDescription:'Choose one placed physical tile. While it has exactly two connected neighbours on perpendicular sides, its scoring operation has ×3 magnitude. The signal only needs to activate the tile; it does not need to turn through it. Break the required shape and this Mod is lost.',description:'Exactly two perpendicular physical connections give ×3 operation magnitude.'});
  register({id:'long-line',category:'topology',topologyRule:'long-line',displayName:'LONG LINE',name:'LONG LINE',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_LONG_LINE_COST',collectionTile:[0,6],collectionCode:'LN',collectionDefaultUnlocked:true,shortDescription:'3+ straight: ×2. 5+: ×3.',rulesDescription:'Choose one placed physical tile. It activates while it has exactly two opposite physical connections. Count the continuous straight physical line through it: 3–4 tiles give ×2 operation magnitude; 5 or more give ×3. The selected signal does not need to have travelled straight beforehand. Break the required shape and this Mod is lost.',description:'A physical straight line of 3–4 tiles gives ×2; 5+ gives ×3.'});
  register({id:'overload',category:'topology',topologyRule:'overload',displayName:'OVERLOAD',name:'OVERLOAD',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_OVERLOAD_COST',collectionTile:[4,4],collectionCode:'OV',collectionDefaultUnlocked:true,shortDescription:'× neighbour count.',rulesDescription:'Choose one placed physical tile. Its operation magnitude is multiplied by its number of connected neighbouring tiles: ×1, ×2, ×3 or ×4. A fully connected cross double reaches ×4. Break the required shape and this Mod is lost.',description:'Operation magnitude × physical connections, capped at ×4.'});
  register({id:'triple-double',category:'signal',displayName:'TRIPLE DOUBLE',name:'TRIPLE DOUBLE',kind:'market-tile-mod',market:true,target:'double',marketCostKey:'MARKET_TRIPLE_DOUBLE_COST',collectionTile:[3,3],collectionCode:'TD',collectionDefaultUnlocked:true,shortDescription:'Full cross: split 3 ways.',rulesDescription:'Choose one eligible non-zero physical double. While it has four physical connections forming a complete cross, its first forward activation each Move processes its operation then clones that signal through the other three exits. Branch outputs are summed. It cannot split again that Move.',description:'A complete double cross splits through all three remaining exits once per Move.'});
  register({id:'double-echo',category:'signal',displayName:'DOUBLE ECHO',name:'DOUBLE ECHO',kind:'market-tile-mod',market:true,target:'double',marketCostKey:'MARKET_DOUBLE_ECHO_COST',collectionTile:[1,1],collectionCode:'DE',collectionDefaultUnlocked:true,shortDescription:'First activation: echo route.',rulesDescription:'Choose one eligible non-zero physical double already placed in the machine. On its first activation each Move, an Echo copies the current Score and follows the already chosen downstream route once. Final Score is Main + Echo. Echoes cannot create Echoes.',description:'Echo the chosen downstream route once.'});
  register({id:'recall',category:'mutation',displayName:'RECALL',name:'RECALL',kind:'market-tile-mod',market:true,target:'tile',eligibility:'mutation-recall',marketCostKey:'MARKET_RECALL_COST',collectionTile:[1,6],collectionCode:'RC',collectionDefaultUnlocked:true,shortDescription:'Once per Stage: return +1 Move.',rulesDescription:'Once per Stage, use RECALL from this tile’s Inspector to remove the physical tile from the machine and return it to an empty Hand slot, or Reserve if Hand is full. Gain +1 Move for the current Round. Its unique ID, printed values, POWER, Star, Circuit rank and RECALL assignment persist. RECALL is unavailable if removal would disconnect the machine or remove an active HINGE pivot. Using a Mutation commits the current machine and clears the pending Undo frame.',description:'Once per Stage, return this tile to Hand or Reserve and gain +1 Move.'});
  register({id:'pair',category:'topology',topologyRule:'pair',displayName:'PAIR',name:'PAIR',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_PAIR_COST',collectionTile:[0,3],collectionCode:'PR',collectionDefaultUnlocked:true,shortDescription:'2×2 pair: both ×2.',rulesDescription:'Choose a placed physical tile. While it has an exact parallel physical neighbour aligned along its full long side so the two dominoes form a 2×2 block of halves, both dominoes have ×2 operation magnitude when activated. Break the required shape and this Mod is lost.',description:'An exact parallel 2×2 domino pair gives both dominoes ×2 operation magnitude.'});
  register({id:'bridge',category:'topology',topologyRule:'bridge',displayName:'BRIDGE',name:'BRIDGE',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_BRIDGE_COST',collectionTile:[0,4],collectionCode:'BR',collectionDefaultUnlocked:true,shortDescription:'Bridge: ×2. First hit +2 Signal.',rulesDescription:'While removing this physical tile would split its connected machine component, its scoring operation has ×2 magnitude. In Signal modes, its first activation each Move also adds +2 Signal. Route history does not matter. Break the required shape and this Mod is lost.',description:'A structural bridge gives ×2 and adds +2 Signal on its first activation each Move.'});
  register({id:'pivot',category:'mutation',displayName:'PIVOT',name:'PIVOT',kind:'market-tile-mod',market:true,target:'tile',eligibility:'mutation-pivot',marketCostKey:'MARKET_PIVOT_COST',collectionTile:[0,5],collectionCode:'PV',collectionDefaultUnlocked:true,shortDescription:'Rotate around either half.',rulesDescription:'Once per Round, use PIVOT from this tile’s Inspector. Choose either half as the anchor and move the other half 90° or 180° around it into any legal position. Matching, collision, machine connectivity and Topology Mod consequences are validated before the move. Active HINGE pivots cannot be moved. Using a Mutation commits the current machine and clears the pending Undo frame.',description:'Once per Round, rotate this physical domino around either anchored half into any legal position.'});
  register({id:'broker',category:'economy',displayName:'BROKER',name:'BROKER',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_BROKER_COST',collectionTile:[1,4],collectionCode:'BO',collectionDefaultUnlocked:true,shortDescription:'Prime it. Skip a Mod: bank −2c.',rulesDescription:'Activate BROKER before a Market to prime it. If that Market closes without buying a Mod, bank −2c of discount, up to −6c total. The stored discount persists and is consumed in full by the next Market Mod purchase. It never discounts Signal, the Tile Shop or tools. BROKER does not change Score.',description:'Prime it before Market; skip buying a Mod to bank −2c, up to −6c.'});
  register({id:'hinge',category:'signal',displayName:'HINGE',name:'HINGE',kind:'market-tile-mod',market:true,target:'tile',eligibility:'hinge',marketCostKey:'MARKET_HINGE_COST',collectionTile:[4,5],collectionCode:'HG',collectionDefaultUnlocked:true,shortDescription:'Activate: swing across pivot.',rulesDescription:'Choose one placed non-zero non-double with a valid mirrored position across an adjacent pivot. On its first activation each Move, HINGE processes its operation then swings to its stored opposite position and the signal continues from there. The new position persists. If that position is occupied or would change an installed Topology Mod, HINGE stays put that Move.',description:'Swing to the stored opposite side of an adjacent pivot once per Move.'});
  register({id:'bank',category:'economy',displayName:'BANK',name:'BANK',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_BANK_COST',collectionTile:[4,6],collectionCode:'BK',collectionDefaultUnlocked:true,shortDescription:'10c: ×2. 20c: ×3.',rulesDescription:'Choose one placed physical tile. Snapshot your wallet at the start of each Move: 10–19 coins gives this tile ×2 operation magnitude and 20+ coins gives ×3. Coins gained or spent during the Move do not change that snapshot.',description:'10–19c gives ×2; 20+c gives ×3 operation magnitude.'});
  register({id:'foundation',category:'economy',displayName:'FOUNDATION',name:'FOUNDATION',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_FOUNDATION_COST',collectionTile:[0,2],collectionCode:'FD',collectionDefaultUnlocked:true,shortDescription:'Survive Markets: +1c, +2c, +3c.',rulesDescription:'Choose one placed physical tile. Each later Market it survives pays more: +1 coin at the first, +2 at the second and +3 at the third. Every later survived Market continues paying +3 coins. Reassigning FOUNDATION resets the ramp. The Market where FOUNDATION is bought does not count, and FOUNDATION does not change Score.',description:'Each later Market survived pays +1c, then +2c, then +3c; later Markets keep paying +3c.'});
  register({id:'knot',category:'topology',topologyRule:'knot',displayName:'KNOT',name:'KNOT',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_KNOT_COST',collectionTile:[1,5],collectionCode:'KN',collectionDefaultUnlocked:true,shortDescription:'2+ loops: ×4.',rulesDescription:'Choose one placed physical tile. While it belongs to at least two distinct deterministic physical cycle signatures, its scoring operation has ×4 magnitude. Route history and Circuit rank do not matter. Break the required shape and this Mod is lost.',description:'Two or more distinct physical cycles through this tile give ×4 operation magnitude.'});
  register({id:'mint',category:'economy',displayName:'MINT',name:'MINT',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_MINT_COST',collectionTile:[5,6],collectionCode:'MT',collectionDefaultUnlocked:true,shortDescription:'First activation each round: +1c.',rulesDescription:'Choose one placed physical tile. The first Move each round that activates this tile and finishes with positive Score pays +1 coin. Echo, split and rebound cannot pay it again that round. MINT does not change Score.',description:'First qualifying activation each round pays +1 coin; Score is unchanged.'});
  return{register,get,all,collection};
});
