(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  root.IterionMods=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const registry=new Map();
  function register(mod){if(!mod?.id)throw new Error('Mod requires id');const displayName=mod.displayName||mod.name||mod.id,shortDescription=mod.shortDescription||mod.description||'',rulesDescription=mod.rulesDescription||mod.description||shortDescription;const normalized={...mod,displayName,shortDescription,rulesDescription,name:mod.name||displayName,description:mod.description||shortDescription};registry.set(mod.id,Object.freeze(normalized));return normalized}
  function get(id){return registry.get(id)||null}
  function all(){return [...registry.values()]}
  register({id:'move',displayName:'+1 MOVE',name:'+1 MOVE',kind:'consumable',cost:3,shortDescription:'Store one extra move.',rulesDescription:'Store one extra move. Spend it whenever you need one additional placement in the current round.',description:'Store one extra move. Use it whenever you need one more placement in the current round.'});
  register({id:'reroll',displayName:'REROLL',name:'REROLL',kind:'consumable',cost:3,shortDescription:'Store one full-hand reroll.',rulesDescription:'Store one full-hand reroll. It remains available until you choose to spend it, replacing the current hand with a new draw.',description:'Store one full-hand reroll. It remains available until you choose to spend it.'});
  register({id:'undo',displayName:'UNDO',name:'UNDO',kind:'consumable',cost:4,shortDescription:'Store one undo.',rulesDescription:'Store one undo. Revert the last placement and its gameplay result. Shop purchases made after that placement remain spent and remain owned.',description:'Store one undo. Revert the last placement; emergency Shop purchases made afterwards are not refunded.'});
  register({id:'double-double',displayName:'DOUBLE DOUBLE',name:'DOUBLE DOUBLE',kind:'market-tile-mod',market:true,target:'double',marketCostKey:'MARKET_DOUBLE_DOUBLE_COST',shortDescription:'Amplify one double already built into the machine.',rulesDescription:'The Market randomly selects one eligible non-zero physical double already placed in the machine. Its first activation each Move applies both halves; later passes in the same Move use the normal double operation.',description:'Randomly modifies one placed non-zero double. Its first activation each Move is amplified.'});
  register({id:'long-run',displayName:'LONG RUN',name:'LONG RUN',kind:'market-machine-mod',market:true,target:'machine',marketCostKey:'MARKET_LONG_RUN_COST',shortDescription:'Long routes pay every activated star once.',rulesDescription:'When the chosen route traverses at least 10 unique physical tiles in one Move, every starred physical tile activated on that route pays its tier once. Otherwise the normal highest-star-wins rule remains.',description:'At 10+ unique routed tiles, all activated stars pay once instead of only the highest tier.'});
  register({id:'zero-memory',displayName:'ZERO MEMORY',name:'ZERO MEMORY',kind:'market-tile-mod',market:true,target:'zero',marketCostKey:'MARKET_ZERO_MEMORY_COST',shortDescription:'A placed zero remembers the previous scoring operation.',rulesDescription:'On this physical zero tile’s first rebound each Move, repeat exactly once the immediately preceding non-zero scoring operation, then continue the normal rebound. Zero charges and routing are unchanged.',description:'On its first rebound each Move, repeat the previous non-zero scoring operation once.'});
  return{register,get,all};
});
