(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  root.IterionMods=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const registry=new Map();
  function register(mod){if(!mod?.id)throw new Error('Mod requires id');const displayName=mod.displayName||mod.name||mod.id,shortDescription=mod.shortDescription||mod.description||'',rulesDescription=mod.rulesDescription||mod.description||shortDescription;const normalized={...mod,displayName,shortDescription,rulesDescription,name:mod.name||displayName,description:mod.description||shortDescription};registry.set(mod.id,Object.freeze(normalized));return normalized}
  function get(id){return registry.get(id)||null}
  function all(){return [...registry.values()]}
  register({id:'move',displayName:'+1 MOVE',name:'+1 MOVE',kind:'consumable',cost:3,shortDescription:'Store one extra move.',rulesDescription:'Store one extra move. Spend it whenever you need one additional placement in the current round.',description:'Store one extra move. Use it whenever you need one more placement in the current round.'});
  register({id:'reroll',displayName:'REROLL',name:'REROLL',kind:'consumable',cost:3,shortDescription:'Store one full-hand reroll.',rulesDescription:'Store one full-hand reroll. It remains available until you choose to spend it, replacing the current hand with a new draw.',description:'Store one full-hand reroll. It remains available until you choose to spend it.'});
  register({id:'undo',displayName:'UNDO',name:'UNDO',kind:'consumable',cost:4,shortDescription:'Store one undo.',rulesDescription:'Store one undo. Revert the last placement and its gameplay result. Purchases made after that placement remain spent and remain owned.',description:'Store one undo. Revert the last placement; purchases made afterwards are not refunded.'});
  register({id:'double-double',displayName:'DOUBLE DOUBLE',name:'DOUBLE DOUBLE',kind:'market-tile-mod',market:true,target:'double',marketCostKey:'MARKET_DOUBLE_DOUBLE_COST',shortDescription:'Amplify one double already built into the machine.',rulesDescription:'Choose one eligible non-zero physical double already placed in the machine. Its first activation each Move applies both halves; later passes in the same Move use the normal double operation.',description:'Choose one placed non-zero double. Its first activation each Move is amplified.'});
  register({id:'long-run',displayName:'LONG CHAIN',name:'LONG CHAIN',kind:'market-machine-mod',market:true,target:'machine',marketCostKey:'MARKET_LONG_RUN_COST',shortDescription:'Long routes pay every activated star once.',rulesDescription:'When the chosen route traverses at least 10 unique physical tiles in one Move, every starred physical tile activated on that route pays its tier once. In Endless, this full payout is limited to 7 qualifying Moves; afterwards the normal highest-star-wins rule returns.',description:'At 10+ unique routed tiles, all activated stars pay once. Endless allows 7 full payouts.'});
  register({id:'zero-port',displayName:'ZERO PORT',name:'ZERO PORT',kind:'market-tile-mod',market:true,target:'zero-port',marketCostKey:'MARKET_ZERO_PORT_COST',shortDescription:'Pair two zero tiles into a teleport link.',rulesDescription:'Install Zero Port on zero tiles. With two installed, a signal reaching a Zero Port teleports to the paired tile instead of rebounding. If the receiving tile is [0|0], the signal duplicates through both physical ends. Buying Zero Port again with a complete pair relocates one endpoint.',description:'Pair two zero tiles into a teleport link; a third purchase relocates one endpoint.'});
  register({id:'parity-exchange',displayName:'PARITY EXCHANGE',name:'PARITY EXCHANGE',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_PARITY_EXCHANGE_COST',shortDescription:'Swap this tile’s odd/even scoring behaviour.',rulesDescription:'Choose one placed physical tile. On that tile only, odd non-zero values add and even non-zero values multiply. Printed values, matching and routing do not change.',description:'Odd values add and even values multiply on this tile.'});
  register({id:'corner',displayName:'CORNER',name:'CORNER',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_CORNER_COST',shortDescription:'Reward building this tile as a physical elbow.',rulesDescription:'Choose one placed physical tile. While it has exactly two connected neighbours on perpendicular sides, its scoring operation has ×3 magnitude. The signal only needs to activate the tile; it does not need to turn through it.',description:'Exactly two perpendicular physical connections give ×3 operation magnitude.'});
  register({id:'long-line',displayName:'LONG LINE',name:'LONG LINE',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_LONG_LINE_COST',shortDescription:'Reward building a continuous physical straight line.',rulesDescription:'Choose one placed physical tile. It activates while it has exactly two opposite physical connections. Count the continuous straight physical line through it: 3–4 tiles give ×2 operation magnitude; 5 or more give ×3. The selected signal does not need to have travelled straight beforehand.',description:'A physical straight line of 3–4 tiles gives ×2; 5+ gives ×3.'});
  register({id:'overload',displayName:'OVERLOAD',name:'OVERLOAD',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_OVERLOAD_COST',shortDescription:'Scale this tile by its physical connections.',rulesDescription:'Choose one placed physical tile. Its operation magnitude is multiplied by its number of connected neighbouring tiles: ×1, ×2, ×3 or ×4. A fully connected cross double reaches ×4.',description:'Operation magnitude × physical connections, capped at ×4.'});
  register({id:'terminal',displayName:'TERMINAL',name:'TERMINAL',kind:'market-tile-mod',market:true,target:'tile',marketCostKey:'MARKET_TERMINAL_COST',shortDescription:'Reward keeping this tile at the machine edge.',rulesDescription:'Choose one placed physical tile. While it has exactly one connected neighbouring tile, its scoring operation has ×3 magnitude. The Mod remains installed if later connections make it inactive.',description:'Exactly one physical connection gives ×3 operation magnitude.'});
  register({id:'triple-double',displayName:'TRIPLE DOUBLE',name:'TRIPLE DOUBLE',kind:'market-tile-mod',market:true,target:'double',marketCostKey:'MARKET_TRIPLE_DOUBLE_COST',shortDescription:'Turn a fully connected double cross into a three-way signal distributor.',rulesDescription:'Choose one eligible non-zero physical double. While it has four physical connections forming a complete cross, its first forward activation each Move clones the post-operation signal through the other three exits. Later activations in that Move behave normally.',description:'A complete double cross sends the signal through all three remaining exits once per Move.'});
  register({id:'double-echo',displayName:'DOUBLE ECHO',name:'DOUBLE ECHO',kind:'market-tile-mod',market:true,target:'double',marketCostKey:'MARKET_DOUBLE_ECHO_COST',shortDescription:'A placed double sends one echo down its chosen downstream route.',rulesDescription:'Choose one eligible non-zero physical double already placed in the machine. On its first activation each Move, an Echo copies the current Score and follows the already chosen downstream route once. Final Score is Main + Echo. Echoes cannot create Echoes.',description:'Choose one non-zero double; its first activation sends one non-recursive Echo down the chosen downstream route.'});
  return{register,get,all};
});
