(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.IterionPresentation=api;
  if(root&&root.document&&root.addEventListener)root.addEventListener('load',()=>api.installUiPolish(root));
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  // Display only. Never feed formatted values or animation timing into the engine.
  const BRAND='MONOID';
  const UNITS=['M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'];
  // Hold the opening activations long enough to teach the arithmetic, then accelerate.
  // The tail still reaches the historic 60 ms floor so large Endless machines stay practical.
  const CASCADE=Object.freeze({introMs:Object.freeze([600,600,560,520,480,440]),tailMs:320,minMs:60,decay:0.70,maxLabels:8,finalMs:500,scoreTweenMs:360});
  function exact(value){return Number.isFinite(value)?Math.round(value).toLocaleString('en-US',{maximumFractionDigits:0}):String(value)}
  function scaledText(value){const decimals=value<10?2:value<1000?1:0,rounded=Number(value.toFixed(decimals));return rounded.toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:decimals})}
  function compact(value){if(!Number.isFinite(value))return String(value);const whole=Math.round(value),sign=whole<0?'-':'',n=Math.abs(whole);if(n<1000000)return exact(whole);let tier=0;while(tier<UNITS.length-1&&n>=100*(10**(6+3*(tier+1))))tier++;const divisor=10**(6+3*tier),scaled=n/divisor;if(tier===UNITS.length-1&&scaled>=100000)return whole.toExponential(2).replace(/\.00e/,'e').replace(/(\.\d)0e/,'$1e').replace('e+','e');return sign+scaledText(scaled)+UNITS[tier]}
  function scoreDisplay(score,target){const targetText=compact(target),text=compact(score),below=score<target;return{score:text,target:targetText,note:below&&score>0&&score/target>=0.95?`${compact(target-score)} to target`:score>=target?'Target reached':'Last move'}}
  function cascadeDelay(index){index=Math.max(0,Math.floor(Number(index)||0));if(index<CASCADE.introMs.length)return CASCADE.introMs[index];return Math.max(CASCADE.minMs,Math.round(CASCADE.tailMs*CASCADE.decay**(index-CASCADE.introMs.length)))}
  function effectLifetime(index){return Math.max(480,cascadeDelay(index)+280)}
  function operationHalf(event,mainOperation){return event.exitHalf??(mainOperation?.piece===event.piece?mainOperation.exitHalf:undefined)}
  function fitFontSize(fontSize,measuredWidth,availableWidth){return measuredWidth>availableWidth?fontSize*Math.max(0,availableWidth)/measuredWidth:fontSize}
  function signalPlan(events){const echo=events.filter(e=>e.type.startsWith('echo-')).map(e=>({...e,type:e.type.slice(5)}));const main=events.filter(e=>!e.type.startsWith('echo-')&&e.type!=='double-echo-result');return{main,echo,result:events.find(e=>e.type==='double-echo-result')||null}}
  function forkBlock(events,start){const fork=events[start].piece,branches=[];let i=start+1;while(i<events.length){const e=events[i];if(e.type==='signal-start'&&e.fork===fork){let j=i+1;while(j<events.length&&!(events[j].type==='signal-end'&&events[j].fork===fork&&events[j].arm===e.arm))j++;if(j>=events.length)return null;branches.push({arm:e.arm,events:events.slice(i+1,j),end:events[j]});i=j+1;continue}if(e.type==='signal-join'&&e.piece===fork)return{branches:branches.sort((a,b)=>a.arm-b.arm),join:e,next:i+1};i++}return null}
  function progressState(score,target){score=Math.max(0,Number(score)||0);target=Math.max(1,Number(target)||1);if(score<target)return{stage:'target',progress:Math.max(0,Math.min(1,score/target)),next:'TARGET'};if(score<target*3)return{stage:'clear',progress:Math.max(0,Math.min(1,(score-target)/(target*2))),next:'×3'};if(score<target*5)return{stage:'star1',progress:Math.max(0,Math.min(1,(score-target*3)/(target*2))),next:'×5'};if(score<target*10)return{stage:'star2',progress:Math.max(0,Math.min(1,(score-target*5)/(target*5))),next:'×10'};return{stage:'star3',progress:1,next:'MAX'}}
  function brandDebugText(text){return String(text||'').replace(/^(?:NOMON|MONOID) DEBUG/m,`${BRAND} DEBUG`)}
  function debugFilename(text){text=brandDebugText(text);const version=(text.match(/^MONOID DEBUG v([^\r\n]+)/m)||[])[1]||'unknown',runId=(text.match(/^Run ID:\s*([^\r\n]+)/m)||[])[1]||'run',safe=s=>String(s).trim().replace(/[^a-zA-Z0-9._-]+/g,'-');return`${BRAND}_DEBUG_v${safe(version)}_${safe(runId)}.txt`}
  function installUiPolish(root){
    const doc=root?.document;if(!doc||root.__nomonUiPolishInstalled)return;root.__nomonUiPolishInstalled=true;
    doc.title=`${BRAND}${root.IterionData?.VERSION?` v${root.IterionData.VERSION}`:''}`;const wordmark=doc.querySelector('.wordmark');if(wordmark)wordmark.textContent=BRAND;
    const style=doc.createElement('style');style.id='nomon-ui-polish';style.textContent=`
      .powerTile.power2{--power-pale:#dbe6ec}.powerTile.power3{--power-pale:#e5ddea}.powerTile.power4{--power-pale:#e8dfbd}
      .domino.powerTile:not(.circuitTile),.piece.powerTile:not(.circuitTile){color:#171717}
      .domino.powerTile:not(.circuitTile)::before,.piece.powerTile:not(.circuitTile)::before{content:"";position:absolute;inset:0;background:var(--power-pale);z-index:0;pointer-events:none}
      .powerTile:not(.circuitTile) .half,.powerTile:not(.circuitTile) .cube{position:relative;z-index:1}
      .powerTile:not(.circuitTile) .pip,.powerTile:not(.circuitTile) .spip{background:#171717;z-index:2}
      .powerTile:not(.circuitTile) .half+.half,.piece.powerTile:not(.circuitTile).h .cube+.cube,.piece.powerTile:not(.circuitTile).v .cube+.cube{border-color:#4b4a45}
      .powerMark{opacity:0!important}
      .circuitRankMark{display:none!important}
      .upgradeDot{display:none!important}
      .overkillTier1{--overkill-color:#4f86b7}.overkillTier2{--overkill-color:#9a70b5}.overkillTier3{--overkill-color:#d39a2f}
      .domino.overkillTier1 .half+.half,.domino.overkillTier2 .half+.half,.domino.overkillTier3 .half+.half{border-top-color:var(--overkill-color)!important;border-top-width:3px!important}
      .piece.h.overkillTier1 .cube+.cube,.piece.h.overkillTier2 .cube+.cube,.piece.h.overkillTier3 .cube+.cube{border-left-color:var(--overkill-color)!important;border-left-width:3px!important}
      .piece.v.overkillTier1 .cube+.cube,.piece.v.overkillTier2 .cube+.cube,.piece.v.overkillTier3 .cube+.cube{border-top-color:var(--overkill-color)!important;border-top-width:3px!important}
      .domino:has(>.upgradeDot.u1) .half+.half{border-top-color:#4f86b7!important;border-top-width:3px!important}
      .domino:has(>.upgradeDot.u2) .half+.half{border-top-color:#9a70b5!important;border-top-width:3px!important}
      .domino:has(>.upgradeDot.u3) .half+.half{border-top-color:#d39a2f!important;border-top-width:3px!important}
      .piece.h:has(>.upgradeDot.u1) .cube+.cube{border-left-color:#4f86b7!important;border-left-width:3px!important}
      .piece.h:has(>.upgradeDot.u2) .cube+.cube{border-left-color:#9a70b5!important;border-left-width:3px!important}
      .piece.h:has(>.upgradeDot.u3) .cube+.cube{border-left-color:#d39a2f!important;border-left-width:3px!important}
      .piece.v:has(>.upgradeDot.u1) .cube+.cube{border-top-color:#4f86b7!important;border-top-width:3px!important}
      .piece.v:has(>.upgradeDot.u2) .cube+.cube{border-top-color:#9a70b5!important;border-top-width:3px!important}
      .piece.v:has(>.upgradeDot.u3) .cube+.cube{border-top-color:#d39a2f!important;border-top-width:3px!important}
      .inspectOverkillPreview{display:flex;align-items:center;justify-content:flex-start;gap:10px;margin:10px 0 2px}.inspectOverkillDomino{display:flex;flex-direction:column;width:46px;border:1.5px solid #1d1d1d;border-radius:6px;overflow:hidden;background:#fbf8f0;box-shadow:1px 2px 3px rgba(25,23,19,.10)}.inspectOverkillHalf{height:34px;display:flex;align-items:center;justify-content:center;font:750 18px/1 ui-monospace,monospace}.inspectOverkillHalf+.inspectOverkillHalf{border-top:3px solid var(--overkill-color)}.inspectOverkillLegend{font:700 11px/1.25 ui-monospace,monospace;letter-spacing:.05em;color:#4c4a44}.inspectOverkillLegend small{display:block;margin-top:3px;font:500 10px/1.3 -apple-system,BlinkMacSystemFont,"SF Pro Display","Helvetica Neue",Arial,sans-serif;letter-spacing:0;color:#77736b}
      .signalValue{min-width:0!important;padding:1px 3px!important;border:0!important;background:transparent!important;box-shadow:none!important;display:flex!important;gap:3px!important;align-items:center!important}
      .signalValue small,.signalValue strong{display:none!important}.signalValue span{font-size:11px!important;font-weight:750!important;padding:2px 4px!important;border:1px solid rgba(21,21,21,.22)!important;border-radius:3px!important;background:rgba(251,250,246,.92)!important;color:#20201d!important}
      .signalValue[data-lane*="."]{display:grid!important;grid-template-columns:auto auto!important;gap:0 5px!important;padding:3px 4px!important;border:1px solid rgba(21,21,21,.2)!important;background:rgba(251,250,246,.92)!important}
      .signalValue[data-lane*="."] small{display:block!important;grid-column:1/-1!important;font-size:7px!important}.signalValue[data-lane*="."] strong{display:inline!important;font-size:11px!important}.signalValue[data-lane*="."] span{border:0!important;background:transparent!important;padding:0!important;font-size:9px!important}
      .signalValue.echoLane{border-style:dashed!important;opacity:.78}.joinFx,.echoJoin,.resonanceFx{font-size:11px!important;background:rgba(251,250,246,.94)!important;box-shadow:none!important;padding:4px 6px!important}
      .scoreProgress{display:block;margin-top:2px;height:11px;position:relative}.scoreProgressTrack{display:block;height:3px;background:#dddcd6;overflow:hidden}.scoreProgressFill{display:block;height:100%;width:0;background:#393934;transition:width .22s linear,background-color .22s ease}.scoreProgressNext{display:block;margin-top:1px;text-align:right;font:650 7px/1.1 ui-monospace,monospace;letter-spacing:.05em;color:#858078}
      .scoreProgress[data-stage="clear"] .scoreProgressFill{background:#6e6b63}.scoreProgress[data-stage="star1"] .scoreProgressFill{background:#4f86b7}.scoreProgress[data-stage="star2"] .scoreProgressFill{background:#9a70b5}.scoreProgress[data-stage="star3"] .scoreProgressFill{background:#d39a2f}
      .scoreCard.scoreLive .scoreValue{font-variant-numeric:tabular-nums}
    `;doc.head.appendChild(style);
    const score=doc.getElementById('score'),scoreDetail=doc.getElementById('scoreDetail'),targetDetail=doc.getElementById('targetDetail'),scoreNote=doc.getElementById('scoreNote'),board=doc.getElementById('board'),runlog=doc.getElementById('runlog'),menuCopy=doc.getElementById('copyrun'),viewRun=doc.getElementById('viewrun'),gameMenu=doc.getElementById('gameMenu'),toast=doc.getElementById('toast'),overlayBody=doc.getElementById('overlayBody'),overlayTitle=doc.getElementById('overlayTitle');if(!score||!scoreDetail||!targetDetail||!board)return;
    const overkillClasses=['overkillTier1','overkillTier2','overkillTier3'];
    const syncOverkillTile=el=>{if(!el?.classList)return;el.classList.remove(...overkillClasses);const dot=[...el.children].find(child=>child.classList?.contains('upgradeDot'));if(!dot)return;for(let tier=1;tier<=3;tier++)if(dot.classList.contains(`u${tier}`)){el.classList.add(`overkillTier${tier}`);break}};
    const syncOverkillTiles=node=>{if(!node)return;if(node.matches?.('.domino,.piece'))syncOverkillTile(node);node.querySelectorAll?.('.domino,.piece').forEach(syncOverkillTile)};
    const syncInspectorPreview=()=>{const inspector=overlayBody?.querySelector('.inspector');if(!inspector)return;const state=inspector.querySelector('.stateRows span'),match=state?.textContent?.match(/^★([1-3])\b/),existing=inspector.querySelector('.inspectOverkillPreview');if(!match){existing?.remove();return}const tier=Number(match[1]),values=overlayTitle?.textContent?.match(/^\[(\d+)\|(\d+)\]$/),a=values?.[1]||'?',b=values?.[2]||'?',key=`${tier}:${a}:${b}`;if(existing?.dataset.key===key)return;const preview=existing||doc.createElement('div');preview.className='inspectOverkillPreview';preview.dataset.key=key;preview.innerHTML=`<div class="inspectOverkillDomino overkillTier${tier}" aria-hidden="true"><div class="inspectOverkillHalf">${a}</div><div class="inspectOverkillHalf">${b}</div></div><div class="inspectOverkillLegend">OVERKILL ${tier}<small>Physical centre line</small></div>`;const hero=inspector.querySelector('.inspectHero');if(!existing)hero?.insertAdjacentElement('afterend',preview)};
    syncOverkillTiles(doc);syncInspectorPreview();
    const visualObserver=new MutationObserver(records=>{let inspectorDirty=false;for(const record of records)for(const node of record.addedNodes){if(node.nodeType!==1)continue;syncOverkillTiles(node);if(node.matches?.('.inspector')||node.querySelector?.('.inspector'))inspectorDirty=true}if(inspectorDirty||overlayBody?.querySelector('.inspector'))syncInspectorPreview()});visualObserver.observe(doc.body,{childList:true,subtree:true});
    const bar=doc.createElement('span');bar.className='scoreProgress';bar.setAttribute('aria-hidden','true');bar.innerHTML='<i class="scoreProgressTrack"><i class="scoreProgressFill"></i></i><i class="scoreProgressNext">TARGET</i>';scoreDetail.insertBefore(bar,scoreNote||null);const fill=bar.querySelector('.scoreProgressFill'),next=bar.querySelector('.scoreProgressNext');
    const ariaNumber=(el,prefix)=>{const label=el?.getAttribute('aria-label')||'',m=label.match(new RegExp(`${prefix}\\s+([-+0-9,.eE]+)`,'i'));return m?Number(m[1].replace(/,/g,'')):NaN};let targetValue=()=>ariaNumber(targetDetail,'Target'),displayed=ariaNumber(scoreDetail,'Score'),raf=0,animating=false;
    const paintProgress=value=>{const state=progressState(value,targetValue());bar.dataset.stage=state.stage;fill.style.width=`${Math.round(state.progress*10000)/100}%`;next.textContent=state.next};if(!Number.isFinite(displayed))displayed=0;paintProgress(displayed);
    const tweenScore=value=>{value=Number(value);if(!Number.isFinite(value))return;if(raf)root.cancelAnimationFrame(raf);const from=Number.isFinite(displayed)?displayed:value,start=root.performance.now(),duration=CASCADE.scoreTweenMs;animating=true;scoreDetail.classList.add('scoreLive');const step=now=>{const t=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-t,3),v=from+(value-from)*eased,visible=value>=from?Math.floor(v):Math.ceil(v);displayed=v;score.textContent=compact(visible);paintProgress(v);if(t<1)raf=root.requestAnimationFrame(step);else{displayed=value;score.textContent=compact(value);paintProgress(value);animating=false;scoreDetail.classList.remove('scoreLive');raf=0}};raf=root.requestAnimationFrame(step)};
    const syncFromUi=()=>{const v=ariaNumber(scoreDetail,'Score');if(Number.isFinite(v)&&!animating){displayed=v;score.textContent=compact(v);paintProgress(v)}else paintProgress(displayed)};new MutationObserver(syncFromUi).observe(scoreDetail,{attributes:true,attributeFilter:['aria-label']});new MutationObserver(()=>paintProgress(displayed)).observe(targetDetail,{attributes:true,attributeFilter:['aria-label']});
    // Keep SCORE live while a single signal is traversing. During T/Echo fan-out it
    // intentionally freezes until the canonical render() commits the joined result;
    // branch values remain visible on the board and engine state stays the authority.
    new MutationObserver(()=>{const live=[...board.querySelectorAll('.signalValue')].filter(el=>Number.isFinite(Number(el.dataset.output)));if(live.length===1)tweenScore(Number(live[0].dataset.output))}).observe(board,{childList:true,subtree:true});
    const feedback=text=>{if(!toast)return;toast.textContent=text;toast.classList.add('show');root.setTimeout(()=>toast.classList.remove('show'),1300)};
    const debugTextFromUi=()=>{let ta=runlog?.querySelector('.runDataText');if(ta)return brandDebugText(ta.value);const wasOpen=runlog?.classList.contains('show');try{viewRun?.click()}catch(_){}ta=runlog?.querySelector('.runDataText');const text=brandDebugText(ta?.value||'');if(!wasOpen&&runlog?.classList.contains('show')){try{viewRun?.click()}catch(_){}}return text};
    const downloadDebug=(text,filename)=>{const blob=new Blob([text],{type:'text/plain'}),url=root.URL.createObjectURL(blob),a=doc.createElement('a');a.href=url;a.download=filename;a.style.display='none';doc.body.appendChild(a);a.click();root.setTimeout(()=>{root.URL.revokeObjectURL(url);a.remove()},0)};
    const shareDebug=async textOverride=>{const text=brandDebugText(typeof textOverride==='string'?textOverride:debugTextFromUi());if(!text){feedback('Debug unavailable');return false}const filename=debugFilename(text),file=new File([text],filename,{type:'text/plain'});if(root.navigator?.share){let canFiles=true;try{if(root.navigator.canShare)canFiles=root.navigator.canShare({files:[file]})}catch(_){canFiles=false}if(canFiles){try{await root.navigator.share({files:[file],title:`${BRAND} DEBUG`});feedback('DEBUG READY');return true}catch(err){if(err?.name==='AbortError')return false}}}try{downloadDebug(text,filename);feedback('DEBUG READY');return true}catch(_){feedback('Debug export failed');return false}};
    const patchRunlog=()=>{const ta=runlog?.querySelector('.runDataText');if(ta)ta.value=brandDebugText(ta.value);const button=runlog?.querySelector('.tool');if(!button||button.dataset.debugShare==='1')return;button.dataset.debugShare='1';button.textContent='SHARE .TXT';button.onclick=()=>shareDebug(runlog.querySelector('.runDataText')?.value||'')};if(runlog){new MutationObserver(patchRunlog).observe(runlog,{childList:true,subtree:true});patchRunlog()}if(menuCopy){menuCopy.textContent='Share debug .txt';menuCopy.onclick=async()=>{try{if(gameMenu?.open)gameMenu.close()}catch(_){}await shareDebug()}}root.NomonUiPolish=Object.freeze({shareDebug,debugTextFromUi,paintProgress,tweenScore,syncOverkillTiles,syncInspectorPreview})
  }
  return Object.freeze({compact,exact,scoreDisplay,cascadeDelay,effectLifetime,operationHalf,fitFontSize,signalPlan,forkBlock,progressState,brandDebugText,debugFilename,installUiPolish,CASCADE,BRAND});
});
