(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.IterionPresentation=api;
  if(root&&root.document&&root.addEventListener)root.addEventListener('load',()=>api.installUiPolish(root));
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  // Display only. Never feed formatted values or animation timing into the engine.
  const BRAND='MONOID';
  const UNITS=['','K','M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'];
  // Early operations are intentionally readable for new players, then the cascade
  // accelerates hard enough that long late-game machines do not become sluggish.
  const CASCADE=Object.freeze({firstMs:600,minMs:60,decay:0.72,maxLabels:8,finalMs:450});
  function exact(value){return Number.isFinite(value)?value.toLocaleString('en-US',{maximumFractionDigits:20}):String(value)}
  function compact(value){if(!Number.isFinite(value))return String(value);const sign=value<0?'-':'',n=Math.abs(value);if(n<1000)return exact(value);let tier=Math.floor(Math.log10(n)/3);if(tier>=UNITS.length)return value.toExponential(2).replace(/\.00e/,'e').replace(/(\.\d)0e/,'$1e').replace('e+','e');let scaled=n/1000**tier,rounded=Number(scaled.toPrecision(3));if(rounded>=1000&&tier<UNITS.length-1){tier++;scaled=n/1000**tier;rounded=Number(scaled.toPrecision(3))}return sign+String(rounded).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')+UNITS[tier]}
  function scoreDisplay(score,target){const targetText=compact(target),text=compact(score),below=score<target;return{score:text,target:targetText,note:below&&score>0&&score/target>=0.95?`${compact(target-score)} to target`:score>=target?'Target reached':'Last move'}}
  function cascadeDelay(index){return Math.max(CASCADE.minMs,Math.round(CASCADE.firstMs*CASCADE.decay**Math.max(0,index)))}
  function effectLifetime(index){return Math.max(400,cascadeDelay(index)*2+40)}
  function operationHalf(event,mainOperation){return event.exitHalf??(mainOperation?.piece===event.piece?mainOperation.exitHalf:undefined)}
  function fitFontSize(fontSize,measuredWidth,availableWidth){return measuredWidth>availableWidth?fontSize*Math.max(0,availableWidth)/measuredWidth:fontSize}
  function signalPlan(events){const echo=events.filter(e=>e.type.startsWith('echo-')).map(e=>({...e,type:e.type.slice(5)}));const main=events.filter(e=>!e.type.startsWith('echo-')&&e.type!=='double-echo-result');return{main,echo,result:events.find(e=>e.type==='double-echo-result')||null}}
  function forkBlock(events,start){const fork=events[start].piece,branches=[];let i=start+1;while(i<events.length){const e=events[i];if(e.type==='signal-start'&&e.fork===fork){let j=i+1;while(j<events.length&&!(events[j].type==='signal-end'&&events[j].fork===fork&&events[j].arm===e.arm))j++;if(j>=events.length)return null;branches.push({arm:e.arm,events:events.slice(i+1,j),end:events[j]});i=j+1;continue}if(e.type==='signal-join'&&e.piece===fork)return{branches:branches.sort((a,b)=>a.arm-b.arm),join:e,next:i+1};i++}return null}
  function progressState(score,target){score=Math.max(0,Number(score)||0);target=Math.max(1,Number(target)||1);if(score<target)return{stage:'target',progress:Math.max(0,Math.min(1,score/target)),next:'TARGET'};if(score<target*3)return{stage:'clear',progress:Math.max(0,Math.min(1,(score-target)/(target*2))),next:'×3'};if(score<target*5)return{stage:'star1',progress:Math.max(0,Math.min(1,(score-target*3)/(target*2))),next:'×5'};if(score<target*10)return{stage:'star2',progress:Math.max(0,Math.min(1,(score-target*5)/(target*5))),next:'×10'};return{stage:'star3',progress:1,next:'MAX'}}
  function brandDebugText(text){return String(text||'').replace(/^(?:NOMON|MONOID) DEBUG/m,`${BRAND} DEBUG`)}
  function debugFilename(text){text=brandDebugText(text);const version=(text.match(/^MONOID DEBUG v([^\r\n]+)/m)||[])[1]||'unknown',runId=(text.match(/^Run ID:\s*([^\r\n]+)/m)||[])[1]||'run',safe=s=>String(s).trim().replace(/[^a-zA-Z0-9._-]+/g,'-');return`${BRAND}_DEBUG_v${safe(version)}_${safe(runId)}.txt`}
  function installUiPolish(root){
    const doc=root?.document;if(!doc||root.__nomonUiPolishInstalled)return;root.__nomonUiPolishInstalled=true;
    doc.title=`${BRAND}${root.IterionData?.VERSION?` v${root.IterionData.VERSION}`:''}`;const wordmark=doc.querySelector('.wordmark');if(wordmark)wordmark.textContent=BRAND;
    const style=doc.createElement('style');style.id='nomon-ui-polish';style.textContent=`
      .powerTile.power2{--power-pale:#dbe6ec}.powerTile.power3{--power-pale:#e5ddea}.powerTile.power4{--power-pale:#e8dfbd}
      .domino.powerTile:not(.circuitTile),.piece.powerTile:not(.circuitTile){color:#171717}
      .domino.powerTile:not(.circuitTile)::before,.piece.powerTile:not(.circuitTile)::before{content:"";position:absolute;inset:0;background:var(--power-pale);z-index:0;pointer-events:none}
      .powerTile:not(.circuitTile) .half,.powerTile:not(.circuitTile) .cube{position:relative;z-index:1}
      .powerTile:not(.circuitTile) .pip,.powerTile:not(.circuitTile) .spip{background:#171717;z-index:2}
      .powerTile:not(.circuitTile) .half+.half,.piece.powerTile:not(.circuitTile).h .cube+.cube,.piece.powerTile:not(.circuitTile).v .cube+.cube{border-color:#4b4a45}
      .powerMark{opacity:0!important}
      .circuitRankMark{display:none!important}
      .upgradeDot{right:auto!important;top:50%!important;left:50%!important;border-radius:0!important;box-shadow:none!important;pointer-events:none;z-index:12}
      .domino>.upgradeDot{width:calc(100% - 6px)!important;height:2px!important;transform:translate(-50%,-50%)}
      .piece.h>.upgradeDot{width:2px!important;height:calc(100% - 4px)!important;transform:translate(-50%,-50%)}
      .piece.v>.upgradeDot{width:calc(100% - 4px)!important;height:2px!important;transform:translate(-50%,-50%)}
      .upgradeDot.u1{background:#4f86b7!important}.upgradeDot.u2{background:#9a70b5!important}.upgradeDot.u3{background:#d39a2f!important}
      .signalValue{min-width:0!important;padding:1px 3px!important;border:0!important;background:transparent!important;box-shadow:none!important;display:flex!important;gap:3px!important;align-items:center!important}
      .signalValue small,.signalValue strong{display:none!important}.signalValue span{font-size:11px!important;font-weight:750!important;padding:2px 4px!important;border:1px solid rgba(21,21,21,.22)!important;border-radius:3px!important;background:rgba(251,250,246,.92)!important;color:#20201d!important}
      .signalValue[data-lane*="."]{display:grid!important;grid-template-columns:auto auto!important;gap:0 5px!important;padding:3px 4px!important;border:1px solid rgba(21,21,21,.2)!important;background:rgba(251,250,246,.92)!important}
      .signalValue[data-lane*="."] small{display:block!important;grid-column:1/-1!important;font-size:7px!important}.signalValue[data-lane*="."] strong{display:inline!important;font-size:11px!important}.signalValue[data-lane*="."] span{border:0!important;background:transparent!important;padding:0!important;font-size:9px!important}
      .signalValue.echoLane{border-style:dashed!important;opacity:.78}.joinFx,.echoJoin,.resonanceFx{font-size:11px!important;background:rgba(251,250,246,.94)!important;box-shadow:none!important;padding:4px 6px!important}
      .scoreProgress{display:block;margin-top:2px;height:11px;position:relative}.scoreProgressTrack{display:block;height:3px;background:#dddcd6;overflow:hidden}.scoreProgressFill{display:block;height:100%;width:0;background:#393934;transition:width .09s linear,background-color .18s ease}.scoreProgressNext{display:block;margin-top:1px;text-align:right;font:650 7px/1.1 ui-monospace,monospace;letter-spacing:.05em;color:#858078}
      .scoreProgress[data-stage="clear"] .scoreProgressFill{background:#6e6b63}.scoreProgress[data-stage="star1"] .scoreProgressFill{background:#4f86b7}.scoreProgress[data-stage="star2"] .scoreProgressFill{background:#9a70b5}.scoreProgress[data-stage="star3"] .scoreProgressFill{background:#d39a2f}
      .scoreCard.scoreLive .scoreValue{font-variant-numeric:tabular-nums}
    `;doc.head.appendChild(style);
    const score=doc.getElementById('score'),scoreDetail=doc.getElementById('scoreDetail'),targetDetail=doc.getElementById('targetDetail'),scoreNote=doc.getElementById('scoreNote'),board=doc.getElementById('board'),runlog=doc.getElementById('runlog'),menuCopy=doc.getElementById('copyrun'),viewRun=doc.getElementById('viewrun'),gameMenu=doc.getElementById('gameMenu'),toast=doc.getElementById('toast');if(!score||!scoreDetail||!targetDetail||!board)return;
    const bar=doc.createElement('span');bar.className='scoreProgress';bar.setAttribute('aria-hidden','true');bar.innerHTML='<i class="scoreProgressTrack"><i class="scoreProgressFill"></i></i><i class="scoreProgressNext">TARGET</i>';scoreDetail.insertBefore(bar,scoreNote||null);const fill=bar.querySelector('.scoreProgressFill'),next=bar.querySelector('.scoreProgressNext');
    const ariaNumber=(el,prefix)=>{const label=el?.getAttribute('aria-label')||'',m=label.match(new RegExp(`${prefix}\\s+([-+0-9,.eE]+)`,'i'));return m?Number(m[1].replace(/,/g,'')):NaN};let targetValue=()=>ariaNumber(targetDetail,'Target'),displayed=ariaNumber(scoreDetail,'Score'),raf=0,animating=false;
    const paintProgress=value=>{const state=progressState(value,targetValue());bar.dataset.stage=state.stage;fill.style.width=`${Math.round(state.progress*10000)/100}%`;next.textContent=state.next};if(!Number.isFinite(displayed))displayed=0;paintProgress(displayed);
    const tweenScore=value=>{value=Number(value);if(!Number.isFinite(value))return;if(raf)root.cancelAnimationFrame(raf);const from=Number.isFinite(displayed)?displayed:value,start=root.performance.now(),duration=95;animating=true;scoreDetail.classList.add('scoreLive');const step=now=>{const t=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-t,3),v=from+(value-from)*eased;score.textContent=compact(v);paintProgress(v);if(t<1)raf=root.requestAnimationFrame(step);else{displayed=value;score.textContent=compact(value);paintProgress(value);animating=false;scoreDetail.classList.remove('scoreLive');raf=0}};raf=root.requestAnimationFrame(step)};
    const syncFromUi=()=>{const v=ariaNumber(scoreDetail,'Score');if(Number.isFinite(v)&&!animating){displayed=v;score.textContent=compact(v);paintProgress(v)}else paintProgress(displayed)};new MutationObserver(syncFromUi).observe(scoreDetail,{attributes:true,attributeFilter:['aria-label']});new MutationObserver(()=>paintProgress(displayed)).observe(targetDetail,{attributes:true,attributeFilter:['aria-label']});
    // Keep SCORE live while a single signal is traversing. During T/Echo fan-out it
    // intentionally freezes until the canonical render() commits the joined result;
    // branch values remain visible on the board and engine state stays the authority.
    new MutationObserver(()=>{const live=[...board.querySelectorAll('.signalValue')].filter(el=>Number.isFinite(Number(el.dataset.output)));if(live.length===1)tweenScore(Number(live[0].dataset.output))}).observe(board,{childList:true,subtree:true});
    const feedback=text=>{if(!toast)return;toast.textContent=text;toast.classList.add('show');root.setTimeout(()=>toast.classList.remove('show'),1300)};
    const debugTextFromUi=()=>{let ta=runlog?.querySelector('.runDataText');if(ta)return brandDebugText(ta.value);const wasOpen=runlog?.classList.contains('show');try{viewRun?.click()}catch(_){}ta=runlog?.querySelector('.runDataText');const text=brandDebugText(ta?.value||'');if(!wasOpen&&runlog?.classList.contains('show')){try{viewRun?.click()}catch(_){}}return text};
    const downloadDebug=(text,filename)=>{const blob=new Blob([text],{type:'text/plain'}),url=root.URL.createObjectURL(blob),a=doc.createElement('a');a.href=url;a.download=filename;a.style.display='none';doc.body.appendChild(a);a.click();root.setTimeout(()=>{root.URL.revokeObjectURL(url);a.remove()},0)};
    const shareDebug=async textOverride=>{const text=brandDebugText(typeof textOverride==='string'?textOverride:debugTextFromUi());if(!text){feedback('Debug unavailable');return false}const filename=debugFilename(text),file=new File([text],filename,{type:'text/plain'});if(root.navigator?.share){let canFiles=true;try{if(root.navigator.canShare)canFiles=root.navigator.canShare({files:[file]})}catch(_){canFiles=false}if(canFiles){try{await root.navigator.share({files:[file],title:`${BRAND} DEBUG`});feedback('DEBUG READY');return true}catch(err){if(err?.name==='AbortError')return false}}}try{downloadDebug(text,filename);feedback('DEBUG READY');return true}catch(_){feedback('Debug export failed');return false}};
    const patchRunlog=()=>{const ta=runlog?.querySelector('.runDataText');if(ta)ta.value=brandDebugText(ta.value);const button=runlog?.querySelector('.tool');if(!button||button.dataset.debugShare==='1')return;button.dataset.debugShare='1';button.textContent='SHARE .TXT';button.onclick=()=>shareDebug(runlog.querySelector('.runDataText')?.value||'')};if(runlog){new MutationObserver(patchRunlog).observe(runlog,{childList:true,subtree:true});patchRunlog()}if(menuCopy){menuCopy.textContent='Share debug .txt';menuCopy.onclick=async()=>{try{if(gameMenu?.open)gameMenu.close()}catch(_){}await shareDebug()}}root.NomonUiPolish=Object.freeze({shareDebug,debugTextFromUi,paintProgress,tweenScore})
  }
  return Object.freeze({compact,exact,scoreDisplay,cascadeDelay,effectLifetime,operationHalf,fitFontSize,signalPlan,forkBlock,progressState,brandDebugText,debugFilename,installUiPolish,CASCADE,BRAND});
});