(function(){
  const E=window.IterionEngine,D=window.IterionData,M=window.IterionMods,GAME=window.IterionGame.createGame(E),{G,H,ARROW}=E;
  const P={0:[],1:[[50,50]],2:[[28,28],[72,72]],3:[[28,28],[50,50],[72,72]],4:[[28,28],[72,28],[28,72],[72,72]],5:[[28,28],[72,28],[50,50],[28,72],[72,72]],6:[[28,23],[72,23],[28,50],[72,50],[28,77],[72,77]]};
  const $=id=>document.getElementById(id),board=$('board'),scoreEl=$('score'),targetEl=$('target'),roundEl=$('roundstat'),movesEl=$('moves'),handEl=$('hand'),hint=$('hint'),rerollBtn=$('reroll'),resetBtn=$('reset'),viewBtn=$('viewrun'),copyBtn=$('copyrun'),runlog=$('runlog'),toastEl=$('toast'),overlay=$('overlay'),overlayTitle=$('overlayTitle'),overlayBody=$('overlayBody'),overlayPrimary=$('overlayPrimary'),overlaySecondary=$('overlaySecondary'),overlayTertiary=$('overlayTertiary'),coinEl=$('coins');
  let viewRun=false,outcomeOverlayNotBefore=0,outcomeTimer=0,drag={active:false,index:-1,tile:null,candidates:[],candidate:null,float:null,lastX:0,lastSign:0,switches:0,shakeStarted:0,lastRotate:0};
  const px=n=>n/G*100+'%',py=n=>n/H*100+'%',wait=ms=>new Promise(r=>setTimeout(r,ms));
  function dots(n,s=false){return P[n].map(([x,y])=>`<i class="${s?'spip':'pip'}" style="left:${x}%;top:${y}%"></i>`).join('')}function mini(t){return`<div class="domino"><div class="half"><div class="spips">${dots(t.a,true)}</div></div><div class="half"><div class="spips">${dots(t.b,true)}</div></div></div>`}function ordered(p){return[...p.cubes].sort((a,b)=>p.axis==='H'?a.x-b.x:a.y-b.y)}
  function pieceEl(p,cls='piece'){let d=document.createElement('div');d.className=cls+' '+(p.axis==='H'?'h':'v');d.style.left=px(p.rect.minx);d.style.top=py(p.rect.miny);d.style.width=px(p.rect.maxx-p.rect.minx);d.style.height=py(p.rect.maxy-p.rect.miny);d.innerHTML=ordered(p).map(c=>`<div class="cube"><div class="pips">${dots(c.v)}</div></div>`).join('');return d}function toast(t){toastEl.textContent=t;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1100)}
  function renderBoard(){const s=GAME.state();board.innerHTML='';s.pieces.forEach(p=>board.appendChild(pieceEl(p)));if(drag.active&&drag.candidate){const c=drag.candidate,p=E.pieceFrom(drag.tile,c.x,c.y,0,c.rr,-1);board.appendChild(pieceEl(p,'piece dragCandidate'))}board.classList.toggle('dragging',drag.active)}
  function renderHand(){const s=GAME.state();handEl.innerHTML='';for(let i=0;i<D.HAND_SIZE;i++){const t=s.hand[i],slot=document.createElement('div');slot.className='handSlot';if(t&&!(drag.active&&drag.index===i)){const b=document.createElement('button');b.className='tile';b.innerHTML=mini(t);b.onpointerdown=e=>startDrag(e,i);slot.appendChild(b)}handEl.appendChild(slot)}}
  function hideOverlay(){overlay.className='overlay'}function clearOutcomeDelay(){outcomeOverlayNotBefore=0;if(outcomeTimer){clearTimeout(outcomeTimer);outcomeTimer=0}}function armOutcomeDelay(){clearOutcomeDelay();outcomeOverlayNotBefore=performance.now()+D.OUTCOME_SCREEN_DELAY_MS;outcomeTimer=setTimeout(()=>{outcomeTimer=0;render()},D.OUTCOME_SCREEN_DELAY_MS+20)}
  function showOverlay(type){const s=GAME.state();overlay.className='overlay show '+type;overlayPrimary.onclick=null;overlaySecondary.onclick=null;overlayTertiary.onclick=null;overlayPrimary.disabled=overlaySecondary.disabled=overlayTertiary.disabled=false;overlayPrimary.style.display='inline-block';overlaySecondary.style.display='none';overlayTertiary.style.display='none';if(type==='reroll'){overlayTitle.textContent='NO LEGAL MOVES';overlayBody.textContent='Tu mano no puede conectar con la máquina.';overlayPrimary.textContent='REROLL HAND';overlayPrimary.onclick=()=>{GAME.reroll();GAME.save();if(GAME.state().blocked)armOutcomeDelay();render()}}else if(type==='market'){overlayTitle.textContent='TRAVELING MARKET';overlayBody.textContent=`${s.coins} coins · elige una oferta o sigue jugando.`;const offers=s.marketOffers.map(id=>M.get(id)).filter(Boolean),buttons=[overlayPrimary,overlaySecondary];buttons.forEach((b,i)=>{const m=offers[i];if(!m){b.style.display='none';return}b.style.display='inline-block';b.textContent=`${m.name} · ${m.cost}c`;b.disabled=s.coins<m.cost;b.onclick=()=>{const r=GAME.buyMarket(m.id);if(!r.ok){toast('No tienes suficientes coins');return}GAME.save();hideOverlay();render();toast(m.name)}});overlayTertiary.style.display='inline-block';overlayTertiary.textContent='SKIP';overlayTertiary.onclick=()=>{GAME.skipMarket();GAME.save();hideOverlay();render()}}else if(type==='clear'){overlayTitle.textContent=s.round===D.TOTAL_ROUNDS-1?'RUN COMPLETE':'ROUND CLEAR';overlayBody.textContent=`Output ${s.score} · Target ${GAME.target()}`;overlayPrimary.textContent=s.round===D.TOTAL_ROUNDS-1?'NEW RUN':'NEXT ROUND';overlayPrimary.onclick=()=>{clearOutcomeDelay();if(s.round===D.TOTAL_ROUNDS-1)GAME.fresh();else GAME.advance();GAME.save();hideOverlay();render()}}else if(type==='failed'){overlayTitle.textContent='ROUND FAILED';overlayBody.textContent=`Output ${s.score} · Target ${GAME.target()}`;overlayPrimary.textContent='NEW RUN';overlayPrimary.onclick=()=>{clearOutcomeDelay();GAME.fresh();GAME.save();hideOverlay();render()};overlaySecondary.style.display='inline-block';overlaySecondary.textContent='COPY RUN';overlaySecondary.onclick=copyRun}}
  function render(){const s=GAME.state();renderBoard();renderHand();scoreEl.textContent=s.score;targetEl.textContent=GAME.target();roundEl.textContent=`${s.round+1}/${D.TOTAL_ROUNDS}`;movesEl.textContent=`${s.roundTurn}/${GAME.maxPlacements()}`;coinEl.textContent=s.coins;rerollBtn.disabled=s.rerollUsed||s.running||s.cleared||s.blocked;rerollBtn.textContent=s.rerollUsed?'Reroll usado':'Reroll mano · 1';hint.textContent=s.cleared?'Ronda superada.':s.needsReroll?'No hay colocaciones legales. Usa el reroll para continuar.':s.blocked?'La ronda ha terminado.':s.pieces.length===0?'Arrastra T1. Haz un pequeño shake izquierda/derecha mientras la mantienes para girarla.':`Construye la máquina. ${GAME.maxPlacements()-s.roundTurn} colocaciones restantes.`;renderLog();if(!s.running){const waiting=(s.cleared||s.blocked)&&performance.now()<outcomeOverlayNotBefore;if(waiting)hideOverlay();else if(s.cleared)showOverlay('clear');else if(s.marketOpen)showOverlay('market');else if(s.needsReroll)showOverlay('reroll');else if(s.blocked)showOverlay('failed');else hideOverlay()}}
  function center(c,r){let p=E.pieceFrom(drag.tile,c.x,c.y,0,c.rr,-1);return{x:(p.rect.minx+p.rect.maxx)/2/G*r.width,y:(p.rect.miny+p.rect.maxy)/2/H*r.height}}function nearest(x,y){let r=board.getBoundingClientRect(),lx=x-r.left,ly=(y-D.DRAG_Y_OFFSET)-r.top;if(lx<0||ly<0||lx>r.width||ly>r.height)return null;let pick=null,d0=1e9;for(const c of drag.candidates){let q=center(c,r),d=Math.hypot(q.x-lx,q.y-ly);if(d<d0){d0=d;pick=c}}return d0<=80?pick:null}
  function maybeShakeRotate(e){const s=GAME.state();if(s.pieces.length)return;const now=performance.now(),dx=e.clientX-drag.lastX;if(Math.abs(dx)>=D.SHAKE_THRESHOLD){const sign=Math.sign(dx);if(drag.lastSign&&sign!==drag.lastSign){if(!drag.shakeStarted||now-drag.shakeStarted>D.SHAKE_WINDOW_MS){drag.switches=1;drag.shakeStarted=now}else drag.switches++;if(drag.switches>=D.SHAKE_SWITCHES&&now-drag.lastRotate>D.SHAKE_COOLDOWN_MS){GAME.rotateRoot();drag.candidates=GAME.candidatesForIndex(drag.index);drag.candidate=null;drag.lastRotate=now;drag.switches=0;drag.shakeStarted=now;if(navigator.vibrate)navigator.vibrate(12);updateFloatRotation();toast(`T1 ${ARROW[GAME.state().rootRR]}`)}}drag.lastSign=sign;drag.lastX=e.clientX}}function updateFloatRotation(){if(drag.float)drag.float.style.setProperty('--rr',GAME.state().rootRR)}
  function startDrag(e,i){if(!GAME.canInteract())return;e.preventDefault();const s=GAME.state(),cs=GAME.candidatesForIndex(i);if(!cs.length)return toast('Esta ficha no tiene posición legal');const f=document.createElement('div');f.className='dragFloat';f.innerHTML=mini(s.hand[i]);document.body.appendChild(f);drag={active:true,index:i,tile:{...s.hand[i]},candidates:cs,candidate:null,float:f,lastX:e.clientX,lastSign:0,switches:0,shakeStarted:performance.now(),lastRotate:0};renderHand();updateFloatRotation();moveDrag(e)}
  function moveDrag(e){if(!drag.active)return;e.preventDefault();maybeShakeRotate(e);if(drag.float){drag.float.style.left=e.clientX+'px';drag.float.style.top=(e.clientY-D.DRAG_Y_OFFSET)+'px'}let c=nearest(e.clientX,e.clientY),o=drag.candidate,changed=(!c)!==(!o)||c&&(!o||c.x!==o.x||c.y!==o.y||c.rr!==o.rr);drag.candidate=c;if(drag.float)drag.float.style.opacity=c?'0':'0.96';if(changed)renderBoard()}
  async function endDrag(e){if(!drag.active)return;moveDrag(e);const i=drag.index,c=drag.candidate;if(drag.float)drag.float.remove();drag={active:false,index:-1,tile:null,candidates:[],candidate:null,float:null};renderBoard();if(!c){renderHand();return}const ctx=GAME.beginPlacement(i,c);if(!ctx.ok){toast('Posición no válida');render();return}renderHand();renderBoard();await animate(ctx.p,ctx.trigger,ctx.sim);GAME.finishPlacement(ctx);GAME.save();if(GAME.state().cleared||GAME.state().blocked)armOutcomeDelay();render();if(GAME.state().cleared)toast(`Round clear · ${GAME.state().score}`)}
  window.addEventListener('pointermove',moveDrag,{passive:false});window.addEventListener('pointerup',endDrag);window.addEventListener('pointercancel',endDrag);function pc(id){return GAME.state().pieces.find(p=>p.id===id)}function fx(x,y,t){let d=document.createElement('div');d.className='opfx';d.style.left=px(x);d.style.top=py(y);d.textContent=t;board.appendChild(d);setTimeout(()=>d.remove(),760)}function finalFx(v){let d=document.createElement('div');d.className='finalfx';d.textContent=v;board.appendChild(d);setTimeout(()=>d.remove(),1050)}
  async function animate(p,trigger,sim){renderBoard();fx((p.rect.minx+p.rect.maxx)/2,(p.rect.miny+p.rect.maxy)/2,`+${trigger}`);await wait(260);for(const e of sim.events||[]){if(e.type==='op'&&e.value!==0){let pp=pc(e.piece),c=pp?.cubes.find(x=>x.half===e.exitHalf);if(c){fx(c.x+1,c.y+1,e.op==='multiply'?`×${e.factor}`:`+${e.add}`);await wait(180)}}else if(e.type==='rebound'){let pp=pc(e.piece),c=pp?.cubes.find(x=>x.v===0)||pp?.cubes[0];if(c){fx(c.x+1,c.y+1,'↩');await wait(180)}}}finalFx(sim.output??trigger);await wait(600)}function renderLog(){runlog.textContent=GAME.debugText();runlog.classList.toggle('show',viewRun)}
  async function copyRun(){const text=GAME.debugText();GAME.save();try{await navigator.clipboard.writeText(text);toast('Run copiada · pega en ChatGPT')}catch(_){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.left='8px';ta.style.right='8px';ta.style.bottom='70px';ta.style.height='140px';ta.style.zIndex='300';document.body.appendChild(ta);ta.focus();ta.select();const ok=document.execCommand('copy');if(ok){ta.remove();toast('Run copiada · pega en ChatGPT')}else{toast('Selecciona y copia el texto');setTimeout(()=>ta.remove(),9000)}}}
  rerollBtn.onclick=()=>{GAME.reroll();GAME.save();if(GAME.state().blocked)armOutcomeDelay();render()};resetBtn.onclick=()=>{clearOutcomeDelay();GAME.fresh();GAME.save();render()};copyBtn.onclick=copyRun;viewBtn.onclick=()=>{viewRun=!viewRun;renderLog()};GAME.save();render();
})();
