(function(){
  const E=window.IterionEngine,D=window.IterionData,M=window.IterionMods,GAME=window.IterionGame.createGame(E),{G,H,ARROW}=E;
  const P={0:[],1:[[50,50]],2:[[28,28],[72,72]],3:[[28,28],[50,50],[72,72]],4:[[28,28],[72,28],[28,72],[72,72]],5:[[28,28],[72,28],[50,50],[28,72],[72,72]],6:[[28,23],[72,23],[28,50],[72,50],[28,77],[72,77]]};
  const $=id=>document.getElementById(id),board=$('board'),scoreEl=$('score'),targetEl=$('target'),roundEl=$('roundstat'),movesEl=$('moves'),handEl=$('hand'),hint=$('hint'),rerollBtn=$('reroll'),resetBtn=$('reset'),viewBtn=$('viewrun'),copyBtn=$('copyrun'),runlog=$('runlog'),toastEl=$('toast'),overlay=$('overlay'),overlayTitle=$('overlayTitle'),overlayBody=$('overlayBody'),overlayPrimary=$('overlayPrimary'),overlaySecondary=$('overlaySecondary'),overlayTertiary=$('overlayTertiary'),coinEl=$('coins');
  let viewRun=false,outcomeOverlayNotBefore=0,outcomeTimer=0,uiBusy=false,autoRerollQueued=false;
  let handFx=Array(D.HAND_SIZE).fill('normal');
  let drag={active:false,index:-1,tile:null,candidates:[],candidate:null,float:null,lastX:0,lastSign:0,switches:0,shakeStarted:0,lastRotate:0};
  const px=n=>n/G*100+'%',py=n=>n/H*100+'%',wait=ms=>new Promise(r=>setTimeout(r,ms));
  document.title=`ITERION v${D.VERSION}`;
  const versionLabel=document.querySelector('header .sub');if(versionLabel)versionLabel.textContent=`v${D.VERSION} · ${D.TOTAL_ROUNDS} ROUNDS`;
  const uxStyle=document.createElement('style');uxStyle.textContent=`.boardMessage{position:absolute;left:50%;top:50%;z-index:90;transform:translate(-50%,-50%);width:90%;text-align:center;font-size:28px;font-weight:900;letter-spacing:.08em;pointer-events:none;animation:boardMsg .9s ease-out forwards}.marketIntro{font-size:12px;color:#5e5a53;margin:0 0 10px}.marketDescriptions{display:grid;gap:7px;margin:0 0 14px;text-align:left}.marketDesc{border:1px solid rgba(0,0,0,.1);border-radius:9px;padding:8px;background:rgba(255,255,255,.35)}.marketDesc strong{display:block;font-size:11px;letter-spacing:.04em}.marketDesc span{display:block;font-size:10px;color:#625e57;line-height:1.3;margin-top:3px}@keyframes boardMsg{0%{opacity:0;transform:translate(-50%,-50%) scale(.7)}20%,65%{opacity:1;transform:translate(-50%,-50%) scale(1)}100%{opacity:0;transform:translate(-50%,-60%) scale(1.06)}}`;document.head.appendChild(uxStyle);
  function dots(n,s=false){return P[n].map(([x,y])=>`<i class="${s?'spip':'pip'}" style="left:${x}%;top:${y}%"></i>`).join('')}
  function mini(t,fx='normal'){const cls=fx==='back'?' back':fx==='reveal'?' reveal':'';return`<div class="domino${cls}"><div class="half"><div class="spips">${dots(t?.a??0,true)}</div></div><div class="half"><div class="spips">${dots(t?.b??0,true)}</div></div></div>`}
  function ordered(p){return[...p.cubes].sort((a,b)=>p.axis==='H'?a.x-b.x:a.y-b.y)}
  function pieceEl(p,cls='piece'){let d=document.createElement('div');d.className=cls+' '+(p.axis==='H'?'h':'v');d.style.left=px(p.rect.minx);d.style.top=py(p.rect.miny);d.style.width=px(p.rect.maxx-p.rect.minx);d.style.height=py(p.rect.maxy-p.rect.miny);d.innerHTML=ordered(p).map(c=>`<div class="cube"><div class="pips">${dots(c.v)}</div></div>`).join('');return d}
  function toast(t){toastEl.textContent=t;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1100)}
  function boardMessage(text,ms=900){const d=document.createElement('div');d.className='boardMessage';d.textContent=text;board.appendChild(d);setTimeout(()=>d.remove(),ms)}
  function renderBoard(){const s=GAME.state();board.innerHTML='';s.pieces.forEach(p=>board.appendChild(pieceEl(p)));if(drag.active&&drag.candidate){const c=drag.candidate,p=E.pieceFrom(drag.tile,c.x,c.y,0,c.rr,-1);board.appendChild(pieceEl(p,'piece dragCandidate'))}board.classList.toggle('dragging',drag.active)}
  function renderHand(){
    const s=GAME.state();handEl.innerHTML='';
    const canGrade=!uiBusy&&!s.running&&!s.cleared&&!s.blocked&&!s.marketOpen&&!s.needsReroll;
    const mask=canGrade?s.hand.map((t,i)=>!!t&&GAME.candidatesForIndex(i).length>0):s.hand.map(Boolean);
    for(let i=0;i<D.HAND_SIZE;i++){
      const t=s.hand[i],slot=document.createElement('div');slot.className='handSlot';
      if(handFx[i]==='hidden'||(drag.active&&drag.index===i)){handEl.appendChild(slot);continue}
      if(handFx[i]==='back'){const shell=document.createElement('div');shell.innerHTML=mini(t||{a:0,b:0},'back');slot.appendChild(shell.firstChild);handEl.appendChild(slot);continue}
      if(t){const b=document.createElement('button');b.className='tile'+(mask[i]?'':' unplayable');b.disabled=!mask[i]||uiBusy;b.innerHTML=mini(t,handFx[i]);b.onpointerdown=e=>startDrag(e,i);slot.appendChild(b)}
      handEl.appendChild(slot)
    }
  }
  function hideOverlay(){overlay.className='overlay'}
  function clearOutcomeDelay(){outcomeOverlayNotBefore=0;if(outcomeTimer){clearTimeout(outcomeTimer);outcomeTimer=0}}
  function armOutcomeDelay(){clearOutcomeDelay();outcomeOverlayNotBefore=performance.now()+D.OUTCOME_SCREEN_DELAY_MS;outcomeTimer=setTimeout(()=>{outcomeTimer=0;render()},D.OUTCOME_SCREEN_DELAY_MS+20)}
  function runSummary(){const x=GAME.snapshot(),turns=x.turns.filter(e=>Number.isInteger(e.turn)),mvp=turns.reduce((b,e)=>!b||e.output>b.output?e:b,null);let addOps=0,multOps=0,rebounds=0;for(const e of turns){addOps+=(e.ops.match(/:\+/g)||[]).length;multOps+=(e.ops.match(/:×/g)||[]).length;rebounds+=e.rebounds||0}return{roundsCleared:x.round.clears.length,totalRounds:x.round.total,tilesPlayed:x.turnCount,bestOutput:x.score.best,mvpTile:mvp?{a:mvp.tile.a,b:mvp.tile.b,output:mvp.output,round:mvp.round,placement:mvp.roundTurn}:null,addOps,multOps,rebounds,rerolls:x.turns.filter(e=>e.type==='reroll').length,purchases:x.turns.filter(e=>e.type==='market-buy').length,coins:x.coins,mods:x.mods}}
  function summaryHtml(){const r=runSummary(),m=r.mvpTile,mods=r.mods.length?r.mods.map(id=>M.get(id)?.name||id).join(', '):'None';return`<div class="summary"><div class="sumCard wide"><div class="sumLabel">MVP TILE</div><div class="sumValue">${m?`[${m.a}|${m.b}] → ${m.output}`:'—'}</div><div class="sumSmall">${m?`Best activation · Round ${m.round}, placement ${m.placement}`:'No placement yet'}</div></div><div class="sumCard"><div class="sumLabel">PROGRESS</div><div class="sumValue">${r.roundsCleared}/${r.totalRounds}</div><div class="sumSmall">Rounds cleared</div></div><div class="sumCard"><div class="sumLabel">TILES USED</div><div class="sumValue">${r.tilesPlayed}</div><div class="sumSmall">${r.rerolls} rerolls · ${r.purchases} buys</div></div><div class="sumCard wide"><div class="sumLabel">SCORE SOURCES</div><div class="sumValue">${r.multOps} multipliers · ${r.addOps} additions</div><div class="sumSmall">${r.rebounds} rebounds · Best output ${r.bestOutput}</div></div><div class="sumCard wide"><div class="sumLabel">BUILD</div><div class="sumValue">${r.coins} coins</div><div class="sumSmall">${mods}</div></div></div>`}
  function marketDescriptions(offers){return `<div class="marketIntro">${GAME.state().coins} coins · Choose one offer or keep playing.</div><div class="marketDescriptions">${offers.map(m=>`<div class="marketDesc"><strong>${m.name}</strong><span>${m.description}</span></div>`).join('')}</div>`}
  function showOverlay(type){
    const s=GAME.state();overlay.className='overlay show '+type;overlayPrimary.onclick=overlaySecondary.onclick=overlayTertiary.onclick=null;overlayPrimary.disabled=overlaySecondary.disabled=overlayTertiary.disabled=false;overlayPrimary.style.display='inline-block';overlaySecondary.style.display=overlayTertiary.style.display='none';
    if(type==='market'){
      overlayTitle.textContent='TRAVELING MARKET';const offers=s.marketOffers.map(id=>M.get(id)).filter(Boolean);overlayBody.innerHTML=marketDescriptions(offers);const buttons=[overlayPrimary,overlaySecondary];buttons.forEach((b,i)=>{const m=offers[i];if(!m){b.style.display='none';return}b.style.display='inline-block';b.textContent=`${m.name} · ${m.cost}c`;b.disabled=s.coins<m.cost;b.onclick=()=>{const r=GAME.buyMarket(m.id);if(!r.ok){toast('Not enough coins');return}GAME.save();hideOverlay();render();toast(m.name)}});overlayTertiary.style.display='inline-block';overlayTertiary.textContent='SKIP';overlayTertiary.onclick=()=>{GAME.skipMarket();GAME.save();hideOverlay();render()};
    }else if(type==='clear'){
      const complete=s.round===D.TOTAL_ROUNDS-1;overlayTitle.textContent=complete?'RUN COMPLETE':'ROUND CLEAR';overlayBody.innerHTML=complete?`<p>Output ${s.score} · Target ${GAME.target()}</p>${summaryHtml()}`:`<p>Output ${s.score} · Target ${GAME.target()}</p>`;overlayPrimary.textContent=complete?'NEW RUN':'NEXT ROUND';overlayPrimary.onclick=()=>{clearOutcomeDelay();if(complete)GAME.fresh();else GAME.advance();GAME.save();hideOverlay();handFx.fill('normal');autoRerollQueued=false;render()};
    }else if(type==='failed'){
      overlayTitle.textContent='ROUND FAILED';overlayBody.innerHTML=`<p>Output ${s.score} · Target ${GAME.target()}</p>${summaryHtml()}`;overlayPrimary.textContent='NEW RUN';overlayPrimary.onclick=()=>{clearOutcomeDelay();GAME.fresh();GAME.save();hideOverlay();handFx.fill('normal');autoRerollQueued=false;render()};overlaySecondary.style.display='inline-block';overlaySecondary.textContent='COPY RUN';overlaySecondary.onclick=copyRun;
    }
  }
  function render(){
    const s=GAME.state();renderBoard();renderHand();scoreEl.textContent=s.score;targetEl.textContent=GAME.target();roundEl.textContent=`${s.round+1}/${D.TOTAL_ROUNDS}`;movesEl.textContent=`${s.roundTurn}/${GAME.maxPlacements()}`;coinEl.textContent=s.coins;rerollBtn.disabled=uiBusy||s.rerollUsed||s.running||s.cleared||s.blocked||s.marketOpen||s.needsReroll;rerollBtn.textContent=s.rerollUsed?'Reroll used':'Reroll hand · 1';hint.textContent=s.cleared?'Round cleared.':s.needsReroll?'No legal placements. Rerolling automatically…':s.blocked?'The round is over.':s.pieces.length===0?'Drag T1. Shake gently left/right while holding it to rotate.':`Build the machine. ${GAME.maxPlacements()-s.roundTurn} placements remaining.`;renderLog();
    if(uiBusy){hideOverlay();return}
    if(!s.running){
      const waiting=(s.cleared||s.blocked)&&performance.now()<outcomeOverlayNotBefore;
      if(waiting)hideOverlay();
      else if(s.cleared)showOverlay('clear');
      else if(s.marketOpen)showOverlay('market');
      else if(s.needsReroll){hideOverlay();if(!autoRerollQueued){autoRerollQueued=true;setTimeout(()=>autoNoMovesReroll(),0)}}
      else if(s.blocked)showOverlay('failed');
      else{autoRerollQueued=false;hideOverlay()}
    }
  }
  function center(c,r){let p=E.pieceFrom(drag.tile,c.x,c.y,0,c.rr,-1);return{x:(p.rect.minx+p.rect.maxx)/2/G*r.width,y:(p.rect.miny+p.rect.maxy)/2/H*r.height}}
  function nearest(x,y){let r=board.getBoundingClientRect(),lx=x-r.left,ly=(y-D.DRAG_Y_OFFSET)-r.top;if(lx<0||ly<0||lx>r.width||ly>r.height)return null;let pick=null,d0=1e9;for(const c of drag.candidates){let q=center(c,r),d=Math.hypot(q.x-lx,q.y-ly);if(d<d0){d0=d;pick=c}}return d0<=80?pick:null}
  function maybeShakeRotate(e){const s=GAME.state();if(s.pieces.length)return;const now=performance.now(),dx=e.clientX-drag.lastX;if(Math.abs(dx)>=D.SHAKE_THRESHOLD){const sign=Math.sign(dx);if(drag.lastSign&&sign!==drag.lastSign){if(!drag.shakeStarted||now-drag.shakeStarted>D.SHAKE_WINDOW_MS){drag.switches=1;drag.shakeStarted=now}else drag.switches++;if(drag.switches>=D.SHAKE_SWITCHES&&now-drag.lastRotate>D.SHAKE_COOLDOWN_MS){GAME.rotateRoot();drag.candidates=GAME.candidatesForIndex(drag.index);drag.candidate=null;drag.lastRotate=now;drag.switches=0;drag.shakeStarted=now;if(navigator.vibrate)navigator.vibrate(12);updateFloatRotation();toast(`T1 ${ARROW[GAME.state().rootRR]}`)}}drag.lastSign=sign;drag.lastX=e.clientX}}
  function updateFloatRotation(){if(drag.float)drag.float.style.setProperty('--rr',GAME.state().rootRR)}
  function startDrag(e,i){if(uiBusy||!GAME.canInteract())return;e.preventDefault();const s=GAME.state(),cs=GAME.candidatesForIndex(i);if(!cs.length)return;const f=document.createElement('div');f.className='dragFloat';f.innerHTML=mini(s.hand[i]);document.body.appendChild(f);drag={active:true,index:i,tile:{...s.hand[i]},candidates:cs,candidate:null,float:f,lastX:e.clientX,lastSign:0,switches:0,shakeStarted:performance.now(),lastRotate:0};renderHand();updateFloatRotation();moveDrag(e)}
  function moveDrag(e){if(!drag.active)return;e.preventDefault();maybeShakeRotate(e);if(drag.float){drag.float.style.left=e.clientX+'px';drag.float.style.top=(e.clientY-D.DRAG_Y_OFFSET)+'px'}let c=nearest(e.clientX,e.clientY),o=drag.candidate,changed=(!c)!==(!o)||c&&(!o||c.x!==o.x||c.y!==o.y||c.rr!==o.rr);drag.candidate=c;if(drag.float)drag.float.style.opacity=c?'0':'0.96';if(changed)renderBoard()}
  async function animateDrawSlot(i){handFx[i]='back';renderHand();await wait(D.DRAW_BLACK_MS);handFx[i]='reveal';renderHand();await wait(390);handFx[i]='normal';renderHand()}
  async function endDrag(e){if(!drag.active)return;moveDrag(e);const i=drag.index,c=drag.candidate;if(drag.float)drag.float.remove();drag={active:false,index:-1,tile:null,candidates:[],candidate:null,float:null};renderBoard();if(!c){renderHand();return}const ctx=GAME.beginPlacement(i,c);if(!ctx.ok){toast('Invalid placement');render();return}const drawAnim=animateDrawSlot(i);renderBoard();await animate(ctx.p,ctx.trigger,ctx.sim);GAME.finishPlacement(ctx);GAME.save();await drawAnim;if(GAME.state().cleared||GAME.state().blocked)armOutcomeDelay();render();if(GAME.state().cleared)toast(`Round clear · ${GAME.state().score}`)}
  window.addEventListener('pointermove',moveDrag,{passive:false});window.addEventListener('pointerup',endDrag);window.addEventListener('pointercancel',endDrag);
  function pc(id){return GAME.state().pieces.find(p=>p.id===id)}
  function fx(x,y,t){let d=document.createElement('div');d.className='opfx';d.style.left=px(x);d.style.top=py(y);d.textContent=t;board.appendChild(d);setTimeout(()=>d.remove(),760)}
  function finalFx(v){let d=document.createElement('div');d.className='finalfx';d.textContent=v;board.appendChild(d);setTimeout(()=>d.remove(),1050)}
  async function animate(p,trigger,sim){renderBoard();fx((p.rect.minx+p.rect.maxx)/2,(p.rect.miny+p.rect.maxy)/2,`+${trigger}`);await wait(260);for(const e of sim.events||[]){if(e.type==='op'&&e.value!==0){let pp=pc(e.piece),c=pp?.cubes.find(x=>x.half===e.exitHalf);if(c){fx(c.x+1,c.y+1,e.op==='multiply'?`×${e.factor}`:`+${e.add}`);await wait(180)}}else if(e.type==='rebound'){let pp=pc(e.piece),c=pp?.cubes.find(x=>x.v===0)||pp?.cubes[0];if(c){fx(c.x+1,c.y+1,'↩');await wait(180)}}}finalFx(sim.output??trigger);await wait(600)}
  async function doReroll(){if(uiBusy)return;uiBusy=true;hideOverlay();handFx.fill('hidden');renderHand();await wait(100);const r=GAME.reroll();if(!r.ok){uiBusy=false;handFx.fill('normal');autoRerollQueued=false;render();return}GAME.save();handFx.fill('back');renderHand();await wait(D.REROLL_BLACK_MS);for(let i=0;i<D.HAND_SIZE;i++){handFx[i]='reveal';renderHand();await wait(D.HAND_REVEAL_STAGGER_MS)}await wait(320);handFx.fill('normal');uiBusy=false;autoRerollQueued=false;if(GAME.state().blocked)armOutcomeDelay();render()}
  async function autoNoMovesReroll(){if(uiBusy||!GAME.state().needsReroll){autoRerollQueued=false;return}uiBusy=true;hideOverlay();renderBoard();boardMessage('NO LEGAL MOVES',900);await wait(160);handFx.fill('hidden');renderHand();await wait(100);const r=GAME.reroll();if(!r.ok){uiBusy=false;handFx.fill('normal');autoRerollQueued=false;render();return}GAME.save();handFx.fill('back');renderHand();await wait(D.REROLL_BLACK_MS);for(let i=0;i<D.HAND_SIZE;i++){handFx[i]='reveal';renderHand();await wait(D.HAND_REVEAL_STAGGER_MS)}await wait(320);handFx.fill('normal');uiBusy=false;autoRerollQueued=false;if(GAME.state().blocked)armOutcomeDelay();render()}
  function renderLog(){runlog.textContent=GAME.debugText();runlog.classList.toggle('show',viewRun)}
  async function copyRun(){const text=GAME.debugText();GAME.save();try{await navigator.clipboard.writeText(text);toast('Run copied · paste it into ChatGPT')}catch(_){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.left='8px';ta.style.right='8px';ta.style.bottom='70px';ta.style.height='140px';ta.style.zIndex='300';document.body.appendChild(ta);ta.focus();ta.select();const ok=document.execCommand('copy');if(ok){ta.remove();toast('Run copied · paste it into ChatGPT')}else{toast('Select and copy the text');setTimeout(()=>ta.remove(),9000)}}}
  rerollBtn.onclick=doReroll;resetBtn.onclick=()=>{if(uiBusy)return;clearOutcomeDelay();GAME.fresh();GAME.save();handFx.fill('normal');autoRerollQueued=false;render()};copyBtn.onclick=copyRun;viewBtn.onclick=()=>{viewRun=!viewRun;renderLog()};GAME.save();render();
})();
