const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),root=path.join(__dirname,'..');
const ui=fs.readFileSync(path.join(root,'ui.js'),'utf8');
const css=fs.readFileSync(path.join(root,'ui-theme.css'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const runtime=fs.readFileSync(path.join(root,'ui-runtime-fixes.js'),'utf8');
const late=fs.readFileSync(path.join(root,'ui-late-polish.js'),'utf8');

assert.match(index,/id="shopButton"[^>]*>TILE SHOP/,'Primary commerce CTA must say TILE SHOP');
assert.doesNotMatch(index,/>Coins\s*</,'Run menu must not label the balance as Coins');
assert.match(index,/class="currencyMark"/,'Initial economy UI must expose the MONOID currency mark');
assert.match(runtime,/TILE SHOP<small><span class="currencyAmount"/,'Runtime UI sync must preserve TILE SHOP and the currency mark');
assert.match(ui,/GAME\.canOpenShop\(\{allowUnaffordable:true\}\)/,'Tile Shop must stay tappable when stock exists but funds are insufficient');
assert.match(ui,/TILE SHOP CLOSED/);assert.match(ui,/INSUFFICIENT FUNDS/);
assert.doesNotMatch(late,/NOT ENOUGH COINS/);

assert.match(css,/\.currencyMark\{[^}]*border:0[^}]*border-radius:50%[^}]*background:currentColor[^}]*-webkit-mask:[^}]*transparent/,'Currency mark needs a solid circular token with a transparent vertical cut');
assert.match(css,/\.currencyMark::before,\.currencyMark::after\{[^}]*content:none[^}]*display:none/,'Currency mark must not retain the old central pip or external strike');
assert.match(ui,/<span class="currencyValue">\$\{escapeHtml\(prefix\+display\)\}<\/span><i class="currencyMark"/,'Currency amounts must keep the sign with the value and place the token last');
assert.match(css,/roundRewardCascade/,'Round reward sources need cascade-like reveal timing');
assert.match(css,/prefers-reduced-motion:reduce[^}]*[\s\S]*roundRewardRow/,'Round reward motion needs a reduced-motion fallback');

assert.match(ui,/overlayTitle\.textContent=complete\?'CLASSIC COMPLETE':'ROUND COMPLETE'/,'Normal clears must say ROUND COMPLETE while final Classic completion stays distinct');
assert.match(ui,/function roundIncomeBreakdown/);
assert.match(ui,/label:'ROUND'/);assert.match(ui,/label:'QUICK CLEAR'/);assert.match(ui,/label:'EXACT TARGET'/);assert.match(ui,/label:'★ ACTIVATIONS'/);assert.match(ui,/label:'MINT'/);
assert.match(ui,/rewardBreakdown/,'Round payoff must read authoritative reward data rather than recalculate gameplay reward rules');
assert.match(ui,/event\.type==='mint-coins'/,'Mint must be explained from the authoritative event log');
assert.match(ui,/roundRewardInline/,'Post-cascade summary must expose earned funds before the result overlay');
assert.match(ui,/roundRewardHeading">EARNED[\s\S]*roundRewardSources[\s\S]*roundRewardTotal[\s\S]*>TOTAL</,'Round payoff must list sources before a larger TOTAL');
assert.match(ui,/roundRewardLeader/,'Round payoff rows must visually connect labels to amounts');
assert.match(ui,/class="roundClearTarget">TARGET \$\{escapeHtml\(compact\(target\)\)\} · ×\$\{escapeHtml\(display\.multiplier\)\}/,'Target value and multiplier must live inside the score block');
assert.doesNotMatch(ui,/class="roundClearMeta"/,'Round payoff must not render a detached Target row below economy');
assert.match(css,/\.roundRewardRow,\.roundRewardTotal\{display:flex[^}]*gap:7px[^}]*width:100%/,'Reward rows and TOTAL must use the same flex geometry');
assert.match(css,/\.roundRewardLeader\{[^}]*flex:1 1 auto[^}]*min-width:18px/,'Reward dotted leaders must flex all the way to each amount');
assert.match(css,/\.roundRewardTotal>span\{font-size:12px[^}]*font-weight:900/,'TOTAL label must carry more visual weight');
assert.match(css,/\.roundRewardTotal>strong\{[^}]*font-size:clamp\(23px,6\.7vw,30px\)/,'TOTAL amount must be smaller than the previous oversized treatment');
assert.match(ui,/roundRewardInlineSource/,'Inline earned sources must render the currency token for every source');
assert.match(ui,/toast\(\`★ \$\{currencyHtml\(result\.upgradeCoins,\{signed:true\}\)\}\`,\{html:true\}\)/,'Star activation toast must identify its reward as currency');
assert.match(css,/animation:roundRewardCascade \.52s ease forwards[^\n]*animation-delay:calc\(\.76s \+ var\(--reward-index,0\)\*\.24s\)/,'Reward cascade must use the slower Phase 2 timing');
assert.match(ui,/function finishRoundAdvanceAnimation/);assert.match(ui,/getAnimations\?\.\(\{subtree:true\}\)/);assert.match(ui,/if\(finishRoundAdvanceAnimation\(\)\)return;proceed\(\)/,'First tap during payoff animation must fast-forward instead of advancing');
assert.match(ui,/ROUND_REWARD_PREVIEW_MS/);
console.log('MONOID economy symbol and round payoff presentation regressions passed');
