const assert=require('assert');
const fs=require('fs');
const path=require('path');
const C=require('../mode-carousel.js');

assert.strictEqual(C.MODES.length,8);
assert.deepStrictEqual(C.MODES.filter(m=>m.available).map(m=>m.id),['classic','eyes','frames','river','loom','peaks','islands']);
assert.strictEqual(C.MODES[0].description,'Classic → Endless → Infinite');
assert.strictEqual(C.MODES[1].name,'THE EYES');
assert.strictEqual(C.MODES[1].description,'1|1 · Signal 6');
assert.strictEqual(C.MODES[2].name,'THE FRAMES');
assert.strictEqual(C.MODES[2].description,'2|2 · Signal 4');
assert.strictEqual(C.MODES[3].name,'THE RIVER');
assert.strictEqual(C.MODES[3].description,'3|3 · Signal 3');
assert.strictEqual(C.MODES[4].name,'THE LOOM');
assert.strictEqual(C.MODES[4].description,'4|4 · Signal 2');
assert.strictEqual(C.MODES[5].name,'THE PEAKS');
assert.strictEqual(C.MODES[5].description,'5|5 · Signal 2');
assert.strictEqual(C.MODES[6].name,'THE ISLANDS');
assert.strictEqual(C.MODES[6].description,'6|6 · Build from Cores');
assert.strictEqual(C.MODES[7].available,false);
assert.strictEqual(C.MODES[7].description,'Not available');
assert.strictEqual(C.clampIndex(-3),0);
assert.strictEqual(C.clampIndex(99),7);
assert.strictEqual(C.stepIndex(0,1),1);
assert.strictEqual(C.stepIndex(7,1),0,'the end of the carousel returns to Classic');
assert.strictEqual(C.stepIndex(0,-1),7,'the carousel remains circular in reverse');
assert.strictEqual(C.cyclicOffset(0,7),1,'Classic is the visible next neighbour after the final mode');
assert.strictEqual(C.cyclicOffset(7,0),-1,'the final mode remains the visible previous neighbour beside Classic');
const nearCenter=C.magnetizeDrag(12);
assert.ok(Math.abs(nearCenter)<12,'a tile close to centre is pulled inward');
const nearNext=C.magnetizeDrag(C.SPACING-16);
assert.ok(nearNext>C.SPACING-16&&nearNext<C.SPACING,'a tile close to the next centre is magnetised toward its snap point');
assert.strictEqual(C.magnetizeDrag(50),50,'free dragging remains direct outside the magnetic zone');
assert.strictEqual(C.SETTLE_APPROACH_MS,250);
assert.strictEqual(C.SETTLE_LAND_MS,140);
assert.strictEqual(C.SETTLE_MIN_APPROACH_MS,140);
assert.strictEqual(C.SETTLE_MIN_LAND_MS,70);
assert.strictEqual(C.SETTLE_MS,390);
assert.strictEqual(C.SETTLE_OVERSHOOT,8);
const settled=C.settleProfile(0,0),near=C.settleProfile(10,0),medium=C.settleProfile(45,0),far=C.settleProfile(C.SPACING,0);
assert.strictEqual(settled.overshoot,0,'exact centre has no synthetic bounce');
assert.ok(near.overshoot>0&&near.overshoot<1,'release near centre has only a tiny overshoot');
assert.ok(medium.overshoot>near.overshoot&&medium.overshoot<far.overshoot,'overshoot scales continuously with remaining travel');
assert.strictEqual(far.overshoot,C.SETTLE_OVERSHOOT,'full travel keeps the current maximum overshoot');
assert.ok(near.approachMs<medium.approachMs&&medium.approachMs<far.approachMs,'approach duration grows with release distance');
assert.ok(near.landMs<medium.landMs&&medium.landMs<far.landMs,'landing duration grows with release distance');
const src=fs.readFileSync(path.join(__dirname,'..','mode-carousel.js'),'utf8');
assert.match(src,/id='modeCarouselFrame'|frame\.id='modeCarouselFrame'/);
assert.match(src,/slides\[0\]\.id='modeClassic'/);
assert.doesNotMatch(src,/id:'infinite-endless'/,'Infinite is a phase of Classic, not a selectable mode');
assert.doesNotMatch(src,/modeCenterBounce/,'snap must not use a scale/click bounce');
assert.match(src,/\.isPulling \.modeSlide\{transition:translate var\(--settle-approach-ms/,'release timing must be adaptive');
assert.match(src,/\.isLanding \.modeSlide\{transition:translate var\(--settle-land-ms/,'landing timing must be adaptive');
assert.match(src,/overshootShift=targetShift\+direction\*profile\.overshoot/,'overshoot direction and amplitude must follow physical travel');
assert.match(src,/strength=t\*t\*\(3-2\*t\)/,'settle strength must ease down strongly near centre');
assert.match(src,/\.modeSlide\.isRemote\{visibility:hidden;pointer-events:none\}\.modeSlide\.isRemote \.modeTile\{visibility:visible\}/,'remote controls stay out of layout checks while their tile visuals remain physically pre-positioned');
assert.match(src,/\.isRebasing \.modeSlide\{transition:none!important\}/,'circular seam rebasing must happen offscreen without crossing the window');
assert.match(src,/modeAvailable=mode=>/,'runtime availability must be profile-aware');
assert.match(src,/startRun\.disabled=!available/,'Start must remain disabled for a profile-locked mode');
assert.match(src,/aria-disabled',item\.kind==='locked'\?'true':'false'/,'profile-locked modes remain tappable for Inspector while the unavailable placeholder stays disabled');
assert.match(src,/__monoidInspectMode/,'mode tiles must bridge long-press inspection into the main UI');
assert.match(src,/startInspectHold/,'mode carousel must distinguish a hold from navigation');
assert.match(src,/LONG_PRESS_MS/,'mode inspection should share the game long-press timing');
assert.match(src,/Tap to inspect/,'selected mode controls should expose tap inspection to assistive labels');
assert.match(src,/if\(offset===0\)[\s\S]*__monoidInspectMode/,'tapping the centred mode must open its Inspector');
assert.match(src,/isTap=Math\.abs\(dx\)<6&&Math\.abs\(projected\)<10/,'pointerup must distinguish a tap from physical carousel dragging');
assert.match(src,/isTap&&tapOffset===0[\s\S]*__monoidInspectMode/,'a true pointer tap on the centred tile must reach Inspector before click suppression');
assert.match(src,/ACTIVE_MODE_KEY/);
const gesture=fs.readFileSync(path.join(__dirname,'..','gesture.js'),'utf8');
assert.match(gesture,/mode-carousel\.js\?v=20261005\.4/);
assert.match(gesture,/data-monoid-modes/);
console.log('mode carousel adaptive physical settle regression tests passed');
