const assert=require('assert');
const fs=require('fs');
const path=require('path');
const C=require('../mode-carousel.js');

assert.strictEqual(C.MODES.length,8);
assert.deepStrictEqual(C.MODES.slice(0,2).map(m=>[m.id,m.available]),[['classic',true],['prototype',true]]);
assert.strictEqual(C.MODES.slice(2).length,6);
assert(C.MODES.slice(2).every(m=>m.available===false&&m.description==='Not available'));
assert.strictEqual(C.clampIndex(-3),0);
assert.strictEqual(C.clampIndex(99),7);
assert.strictEqual(C.stepIndex(0,1),1);
assert.strictEqual(C.stepIndex(7,1),0,'the end of the carousel returns to Classic');
assert.strictEqual(C.stepIndex(0,-1),7,'the carousel remains circular in reverse');
assert.strictEqual(C.cyclicOffset(0,7),1,'Classic is the visible next neighbour after the final mode');
assert.strictEqual(C.cyclicOffset(7,0),-1,'the final mode remains the visible previous neighbour beside Classic');
const nearCenter=C.magnetizeDrag(12);
assert.ok(Math.abs(nearCenter)<12,'a tile close to centre is pulled inward');
const nearNext=C.magnetizeDrag(C.SPACING-16);
assert.ok(nearNext>C.SPACING-16&&nearNext<C.SPACING,'a tile close to the next centre is magnetised toward its snap point');
assert.strictEqual(C.magnetizeDrag(50),50,'free dragging remains direct outside the magnetic zone');
const src=fs.readFileSync(path.join(__dirname,'..','mode-carousel.js'),'utf8');
assert.match(src,/id='modeCarouselFrame'|frame\.id='modeCarouselFrame'/);
assert.match(src,/slides\[0\]\.id='modeClassic'/);
assert.match(src,/modeTilePrototype/);
assert.match(src,/modeCenterBounce/,'snap must include a restrained centre bounce');
assert.match(src,/\.isDragging \.modeSlide\{transition:none\}/,'dragging must track the pointer without transition lag');
assert.match(src,/startRun\.disabled=!mode\.available/);
assert.match(src,/ACTIVE_MODE_KEY/);
const gesture=fs.readFileSync(path.join(__dirname,'..','gesture.js'),'utf8');
assert.match(gesture,/mode-carousel\.js\?v=20260917\.3/);
assert.match(gesture,/data-monoid-modes/);
console.log('mode carousel magnetic snap and circular wrap regression tests passed');
