const assert=require('assert');
const fs=require('fs');
const path=require('path');
const read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const manifest=JSON.parse(read('manifest.webmanifest')),build=JSON.parse(read('build.json')),pwa=read('pwa.js'),sw=read('sw.js'),gesture=read('gesture.js'),updates=read('update-check.js'),extras=read('ui-extras.js'),ux=read('ux-pass.css');
assert.strictEqual(manifest.name,'MONOID');
assert.strictEqual(manifest.display,'standalone');
assert.deepStrictEqual(manifest.display_override.slice(0,2),['fullscreen','standalone']);
assert.strictEqual(manifest.start_url,'./');assert.strictEqual(manifest.scope,'./');
const sizes=new Set(manifest.icons.map(i=>i.sizes));assert(sizes.has('192x192'));assert(sizes.has('512x512'));
assert.strictEqual(build.version,'0.31.1');assert.strictEqual(build.build,'20260915.4');
assert.match(pwa,/SHELL_BUILD='20260915\.4'/);assert.match(pwa,/beforeinstallprompt/);assert.match(pwa,/display-mode: fullscreen/);assert.match(pwa,/display-mode: standalone/);assert.match(pwa,/popstate/);assert.match(pwa,/menuButton/);assert.match(pwa,/serviceWorker\.register\(`sw\.js\?v=\$\{SHELL_BUILD\}`/);assert.match(pwa,/ui-extras\.js\?v=\$\{SHELL_BUILD\}/);
assert.match(updates,/CURRENT_BUILD='20260915\.4'/);assert.match(updates,/build\.json\?ts=/);assert.match(updates,/CHECK FOR UPDATES/);assert.match(updates,/UPDATE AVAILABLE/);assert.match(updates,/RELOAD & UPDATE/);assert.match(updates,/iterion\.activeRun\.v1/);assert.match(updates,/_monoidUpdate/);
assert.match(sw,/MONOID_SW='monoid-dev-network-v2'/);assert.match(sw,/_monoidFresh/);assert.match(sw,/Date\.now\(\)/);assert.match(sw,/Math\.random\(\)/);assert.match(sw,/cache:'no-store'/);assert.doesNotMatch(sw,/caches\.open|addAll/,'development PWA must not pin stale application assets');
assert.match(gesture,/pwa\.js\?v=20260915\.4/);assert.match(gesture,/update-check\.js\?v=20260915\.4/);
assert.match(extras,/BUILD_ID='20260915\.4'/);assert.match(extras,/button\.hidden!==hidden/);assert.match(extras,/attributeFilter:\['class','hidden'\]/);assert.match(extras,/tutorialHubButton/);assert.match(extras,/GAME MECHANICS · 3 MIN/);assert.match(extras,/MODIFIERS · 2 MIN/);assert.match(extras,/DOUBLE DOUBLE/);assert.match(extras,/DOUBLE ECHO/);assert.match(extras,/ZERO MEMORY/);assert.match(extras,/LONG CHAIN/);assert.match(extras,/modifierTutorGameTile/);assert.match(extras,/modifierTutorMachine/);assert.match(extras,/NEXT · GAME MECHANICS/);assert.match(extras,/NEXT · MODIFIERS/);assert.match(extras,/menu\.textContent='MENU'/);
assert.match(ux,/\.titleCard h1\{visibility:hidden\}/);assert.match(ux,/data-monoid-animated="true"/);assert.match(ux,/grid-template-columns:minmax\(0,1fr\) 54px/);assert.match(ux,/\.domino>\.tileModMark\{font-size:13px!important\}/);
console.log('MONOID PWA fresh bootstrap, update check, title preflight, board-led UI and tutorial hub regression: ok');
