const fs=require('fs');
const path=require('path');
const assert=require('assert');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
assert.doesNotMatch(ui,/function showNoMoves\(\)/,'no-legal reroll prompt must not exist after automatic recovery');
assert.doesNotMatch(ui,/s\.needsReroll\)showNoMoves/,'render path must not wait for reroll confirmation');
assert.match(ui,/NO LEGAL MOVES · REROLL USED/,'automatic reroll should give concise player feedback');
const start=ui.indexOf('function showFailed(){'),end=ui.indexOf('\n\n  function render(){',start);assert(start>=0&&end>start);const failed=ui.slice(start,end);
assert.match(failed,/id="downloadFailedRun"/);assert.match(failed,/DOWNLOAD RUN \.TXT/);assert.match(failed,/NomonUiPolish\?\.shareDebug/);assert.match(failed,/MACHINE STALLED/);assert.match(failed,/ENDLESS OVER/);assert.match(failed,/No legal continuation remains and no Rerolls are left/);assert.match(failed,/recovery\.shopRescue/);assert.match(failed,/\+1 MOVE/);assert.match(failed,/!noLegal&&GAME\.canUndo/);assert.match(failed,/!noLegal&&GAME\.canOpenShop/);assert.match(failed,/setNewRunButton/);
console.log('ui failure export and stalled-state regression: ok');
