const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'..','ui-late-polish.js'),'utf8');
assert.match(source,/BUILD_ID='20260916\.2'/);
assert.match(source,/MAX_MARKET_TILES=3/,'Market previews must be capped at three visible physical tiles');
assert.match(source,/RANDOM FROM · \$\{count\}/,'Market must label the physical pool as random, not selectable');
assert.match(source,/additional random recipients/,'Market must expose a +N overflow count');
assert.match(source,/marketAssignments \.marketTile/,'Assigned physical modifiers must come from canonical Market state');
assert.match(source,/marketAssignedGroup/);assert.match(source,/marketPoolGroup/,'Assigned and random pool groups must remain distinct');
assert.match(source,/offer\.replaceChildren\(head,description,context\)/,'Each offer must be rebuilt into one authoritative three-band structure');
assert.match(source,/marketOfferAction/);assert.match(source,/min-height:44px/,'Market actions must retain mobile touch height');
assert.match(source,/id==='long-run'&&endless/);assert.match(source,/7 FULL PAYOUTS IN ENDLESS/,'Long Chain must expose its relevant Endless limit');
assert.match(source,/marketMachineTag/);assert.match(source,/>MACHINE</,'Long Chain must present as a machine modifier');
assert.match(source,/assigned randomly from the shown pool/,'Random assignment disclosure must remain visible');
assert.match(source,/domino\.circuitTile>\.tileModMark/,'Market Circuit modifiers must keep high-contrast lettering');
assert.match(source,/EXTREME_THRESHOLD=1e27/);assert.match(source,/toExponential\(2\)/,'Extreme Endless numbers must use scientific notation');
assert.match(source,/width:clamp\(108px,29\.3vw,126px\)/,'MONOID header width should tune to the 14 Pro Max Dynamic Island reference');
assert.doesNotMatch(source,/IterionEngine|finishPlacement|buyMarketMod\s*=/,'Late polish must not redefine engine, placement or commerce behaviour');
console.log('MONOID late UI polish source regression: ok');
