const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'..','ui-late-polish.js'),'utf8');
assert.match(source,/BUILD_ID='20261005\.1'/);
assert.match(source,/\.compactCommerceModal \.marketOfferGrid\{display:grid!important;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/,'Market must use a compact two-column card grid');
assert.match(source,/\.compactCommerceModal \.shopTileOfferGrid\{display:grid!important;grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/,'Tile Shop must keep four next-set pieces visible without prose rows');
assert.match(source,/\.compactCommerceModal \.shopCompactOffer\{display:grid!important;grid-template-columns:1fr!important/,'Tile Shop cards must override the legacy side-by-side layout and centre the physical tile');
assert.match(source,/marketOfferPayoff/);assert.match(source,/marketOfferVisual/,'Market cards must carry a visual Mod diagram band');assert.match(source,/progressionRewardDialog/,'Unlocks need a dedicated reward surface');assert.match(source,/min-height:44px/,'Market actions must retain mobile touch height');
assert.doesNotMatch(source,/offer\.replaceChildren\(head,description,visual,context\)/,'Late polish must not re-inject the verbose legacy Market structure');
assert.doesNotMatch(source,/description\.textContent=guide\?guide\.market:/,'Market descriptions belong in Inspector, not late-polish cards');
assert.match(source,/offer\.classList\.add\('marketStructuredOffer','marketCompactOffer'\)/,'Late polish may tag compact cards but must not rebuild gameplay UI');
assert.match(source,/domino\.compactPreview\.circuitTile>\.tileModMark/,'Compact Circuit modifiers must keep high-contrast lettering');
assert.match(source,/color:var\(--circuit-pip,#fff\)!important/,'Circuit Mod lettering must reuse the Circuit pip colour');
assert.match(source,/modFaceReveal/,'Board Mod reveal should have a lightweight face-flip transition');
assert.match(source,/domino\.compactPreview>\.half\{width:100%!important/,'Compact halves must fit their own domino, not inherit hand widths');
assert.match(source,/domino\.compactPreview>\.half>\.spips\{inset:16%!important;opacity:1!important/,'Compact pips must remain centred and fully opaque');
assert.match(source,/shopOfferInspect \.domino\.compactPreview\{width:30px!important;height:auto!important[^}]*aspect-ratio:1\/2!important/,'Tile Shop pieces must use the rendered Hand geometry');
assert.match(source,/shopOfferInspect \.domino\.compactPreview>\.half\{width:100%!important;height:50%!important/,'Tile Shop halves must follow the Hand half geometry');
assert.match(source,/shopOfferInspect \.domino\.compactPreview\{width:26px!important\}/,'Short-screen Tile Shop width must mirror the short-screen Hand');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
assert.match(ui,/mini\(t,'normal',true\)/,'Commerce physical tiles use the shared compact renderer');
assert.match(ui,/mini\(shopRevealTile,'reveal',true\)/,'Shop reveals use the same compact renderer');
assert.match(ui,/mini\(\{a:0,b:0\},'back',true\)/,'Face-down Shop previews keep the compact mode');
assert.match(ui,/shopTileOffer shopCompactOffer exactShopOffer/,'Visible next-set tiles need the centred Shop composition');
assert.doesNotMatch(ui,/shopCompactOffer"><button[^\n]+<strong>\[\$\{t\.a\}\|\$\{t\.b\}\]<\/strong>/,'Visible Shop tiles must not repeat their printed values as text');
assert.match(ui,/openShopOfferInspector/);assert.match(ui,/openMarketOfferInspector/,'Shop and Market must route exact explanations through Inspector');
assert.match(ui,/guide\?\.market/,'Market cards must use the concise canonical Mod copy');assert.match(ui,/MG\?\.diagramHtml\?\./,'Market cards must reuse canonical Mod diagrams');assert.match(ui,/queueProgressionReward/,'Mode progression must feed the dedicated reward reveal');assert.match(ui,/persistGame\(\{suppressProgressionReward:true\}\)/,'Starting or restoring a run must not fabricate a fresh reward reveal');assert.match(source,/progressionRewardSurfaceReady/,'Reward reveals must defer behind active game surfaces');
assert.match(ui,/TAP AN OFFER TO INSPECT/);assert.match(ui,/compactCommerceModal/);
assert.match(ui,/function bindInspectorTap\(element,open\)/,'Non-game commerce surfaces need one reusable tap Inspector binding');
assert.match(ui,/adapterQuestion[^>]*>\?<\/b>/,'Unresolved Adapter halves must render question marks instead of normal-looking pips');
assert.match(ui,/\[\?\|\?\]/,'Adapter Inspector must use the same unresolved question-mark identity');
assert.match(ui,/MOD_FACE_REVEAL_MS=3000,modFaceRevealUntil=new Map\(\),modFaceRevealTimers=new Map\(\)/,'Each Mod tile reveal needs independent ephemeral timing');
assert.match(ui,/else if\(meta\.kind==='board'\)revealModFace\(meta\.tileId\)/,'Short board taps should reveal Mod faces without replacing long-press Inspector');
assert.match(ui,/revealed\?' modFaceRevealed':modClass\(p\.tile\)/,'Revealed Mods must render through the canonical front-face classes');
assert.match(ui,/\(revealed\?'':tileModMarks\(p\.tile\)\)/,'Revealed Mods must hide reverse lettering while their printed values are visible');
assert.match(ui,/model\.phasePosition==='between'&&halves\.length===2/,'Endless must place infinity between the two domino halves when a mode has pips');
assert.match(ui,/modeIndicatorInfinityBridge/,'Infinity bridge needs a dedicated composition hook instead of a trailing phase glyph');
const theme=fs.readFileSync(path.join(__dirname,'..','ui-theme.css'),'utf8');
assert.match(theme,/\.modeIndicator\{[^}]*top:32px[^}]*height:12px[^}]*color:var\(--ink\)[^}]*opacity:\.76/,'Mode identity must sit lower, larger and stronger beneath MONOID');
assert.match(theme,/\.modeIndicatorHalf\{width:12px;height:12px[\s\S]*repeat\(3,3px\)/,'Mode pip halves must be materially larger than the first HUD pass');
assert.match(theme,/\.modePip\{width:3px;height:3px/,'Mode pips must remain legible on phone screens');
assert.match(theme,/\.modeIndicatorInfinityBridge\{position:static;font-size:14px/,'Infinity must occupy the centre between mode halves');
assert.match(source,/EXTREME_THRESHOLD=1e27/);assert.match(source,/toExponential\(2\)/,'Extreme Endless numbers must use scientific notation');
assert.match(source,/width:clamp\(108px,29\.3vw,126px\)/,'MONOID header width should tune to the 14 Pro Max Dynamic Island reference');
assert.doesNotMatch(source,/IterionEngine|finishPlacement|buyMarketMod\s*=/,'Late polish must not redefine engine, placement or commerce behaviour');
console.log('MONOID late UI polish source regression: ok');

const runtime=fs.readFileSync(path.join(__dirname,'..','ui-runtime-fixes.js'),'utf8');
assert.match(ui,/function modClass\(t\)\{return tileView\(t\)\.modifiers\.length\?' modTile':''\}/,'Tiles with a physical Mod need one explicit presentation class');
assert.match(ui,/zeroEndpoint/,'Zero endpoints must survive the reverse-face abstraction');
assert.match(runtime,/\.app \.modTile.*--mod-body:#11110f/s,'Mod reverse must be black');
assert.match(runtime,/\.piece\.modTile:has\(>\.tileModMark\) \.pips[\s\S]*opacity:0!important/,'Mod reverse must hide printed values');
assert.match(runtime,/\.domino\.modTile>\.half\+\.half\{border-top-color:transparent!important\}/,'Mod reverse must remove the centre divider visually');
assert.match(runtime,/Circuit material is grey/,'Circuit tiles must use the agreed grey material');
assert.match(runtime,/Existing Star tier line moves from the physical centre to the whole perimeter/,'Star tier must move to the perimeter on Mod tiles');
assert.match(runtime,/\.modTile>\.zeroEndpoint::after/,'Zero must remain readable as a white endpoint line');
assert.match(runtime,/\.commerceModal \.domino\.compactPreview\.modTile>\.tileModMark/,'Compact Market Mods must keep the reverse-face white label');
assert.match(runtime,/Circuit rank colour remains visible on the Mod reverse/,'Circuit colour must be owned by the authoritative reverse-face layer');
assert.match(runtime,/\.app \.circuitTile\.modTile>\.tileModMark,[\s\S]*color:var\(--circuit-pip,#fff\)!important/,'Circuit Mod letters must match their Circuit pip colour');
assert.match(runtime,/\.app \.piece\.modTile:has\(>\.tileModMark\) \.pips/,'Mod reverse must outrank legacy visible-pip styling');
assert.match(runtime,/body\.endlessPalette \.app \.domino\.modTile>\.half\+\.half/,'Endless POWER styling must not restore the Mod divider');
