const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'ux-pass.css'),'utf8');
const ux=fs.readFileSync(path.join(root,'ux-pass.js'),'utf8');
assert.match(index,/<title>MONOID<\/title>/);
assert.match(index,/<span class="wordmark">MONOID<\/span>/);
assert.match(index,/ux-pass\.css\?v=entry-0311/);
assert.match(index,/ux-pass\.js\?v=entry-0311/);
assert.match(index,/id="systemsTutorial"/);
assert.match(index,/LEARN BASICS · 2 MIN/);
assert.match(index,/SYSTEMS TUTORIAL · 3 MIN/);
assert.match(css,/\.selectionDouble i:after\{display:none!important\}/);
assert.match(css,/monoidCommerceActive/);
assert.match(css,/\.boardCoachLayer/);
assert.match(css,/body\.monoidTourActive::before/);
assert.match(css,/\.tile\.tutorialLocked/);
assert.match(ux,/THE MACHINE/);
assert.match(ux,/BUILD\. ROUTE\. SCORE\./);
assert.match(ux,/THE MACHINE CONTINUES\./);
assert.match(ux,/shake left ↔ right to rotate it/);
assert.match(ux,/Connect the 2 wherever you want/);
assert.match(ux,/EXTEND THE ARM/);
assert.match(ux,/T-SPLIT/);
assert.match(ux,/CIRCUITS/);
assert.match(ux,/MODIFIERS/);
assert.match(ux,/POWER/);
assert.match(ux,/MACHINE EVOLUTION/);
assert.match(ux,/primeSystemsGame/);
assert.match(ux,/g2-d1-2/);
assert.match(ux,/Adds one new physical domino to your set/);
assert.match(ux,/game\.candidatesForIndex=function\(i\)\{if\(i!==0\)return\[\];return candidates\(i\)\}/,'Basics must expose every canonical legal candidate for the guided tile');
assert.doesNotMatch(ux,/return list\.filter\(c=>c\.x===/,'Basics must not force a hidden tutorial coordinate');
console.log('ux onboarding presentation regression OK');
