const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'ux-pass.css'),'utf8');
const ux=fs.readFileSync(path.join(root,'ux-pass.js'),'utf8');
assert.match(index,/<title>MONOID<\/title>/);
assert.match(index,/<span class="wordmark">MONOID<\/span>/);
assert.match(index,/ux-pass\.css\?v=entry-0311/);
assert.match(index,/ux-pass\.js\?v=entry-0311/);
assert.match(css,/\.selectionDouble i:after\{display:none!important\}/);
assert.match(css,/monoidCommerceActive/);
assert.match(css,/\.boardCoachLayer/);
assert.match(css,/body\.monoidTourActive::before/);
assert.match(css,/\.tile\.tutorialLocked/);
assert.match(ux,/THE MACHINE/);
assert.match(ux,/BUILD\. ROUTE\. SCORE\./);
assert.match(ux,/THE MACHINE CONTINUES\./);
assert.match(ux,/Every machine starts with a Double/);
assert.match(ux,/EVEN adds\. ODD multiplies/);
assert.match(ux,/EXTEND THE ARM/);
assert.match(ux,/T-SPLIT/);
assert.match(ux,/Adds one new physical domino to your set/);
assert.doesNotMatch(ux,/beginPlacement\s*\(/,'presentation pass must not perform placements');
assert.doesNotMatch(ux,/\.state\(\)\.[A-Za-z0-9_]+\s*=(?!=)/,'presentation pass must not mutate canonical state directly');
console.log('ux onboarding presentation regression OK');
