const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'ui-theme.css'),'utf8');
const ux=fs.readFileSync(path.join(root,'ux-pass.js'),'utf8');
const controller=fs.readFileSync(path.join(root,'tutorial-controller.js'),'utf8');
assert.match(index,/<title>MONOID<\/title>/);
assert.match(index,/<span class="wordmark">MONOID<\/span>/);
assert.match(index,/ui-theme\.css\?v=20260918\.11/);
assert.doesNotMatch(index,/ux-pass\.css/);
assert.strictEqual(fs.existsSync(path.join(root,'ux-pass.css')),false);
assert.match(index,/tutorial-controller\.js\?v=entry-0311/);assert.match(index,/tutorial-controller\.js\?v=entry-0311[\s\S]*ux-pass\.js\?v=20260918\.11/);
assert.match(index,/id="systemsTutorial"/);
assert.match(index,/LEARN BASICS · 2 MIN/);
assert.match(index,/SYSTEMS TUTORIAL · 3 MIN/);
assert.match(css,/\.selectionDouble i:after\{display:none!important\}/);
assert.match(css,/monoidCommerceActive/);
assert.match(css,/\.boardCoachLayer/);
assert.match(css,/body\.monoidTourActive::before/);
assert.match(css,/\.tile\.tutorialLocked/);
assert.match(ux,/THE MACHINE/);
assert.match(ux,/BUILD\. ROUTE\. SCORE\./);
assert.match(ux,/THE MACHINE CONTINUES\./);
assert.match(ux,/shake left ↔ right to rotate it/);
assert.match(ux,/Connect the 2 wherever you want/);
assert.match(ux,/EXTEND THE ARM/);
assert.match(ux,/T-SPLIT/);
assert.match(ux,/CIRCUITS/);
assert.match(ux,/MODIFIERS/);
assert.match(ux,/POWER/);
assert.match(ux,/MACHINE EVOLUTION/);
assert.match(controller,/primeSystemsGame/);
assert.match(controller,/g2-d1-2/);
assert.match(ux,/Adds one new physical domino to your set/);
assert.match(controller,/game\.candidatesForIndex=function\(i\)\{if\(i!==0\)return\[\];return candidates\(i\)\}/,'Basics must expose every canonical legal candidate for the guided tile');
assert.doesNotMatch(controller,/return list\.filter\(c=>c\.x===/,'Basics must not force a hidden tutorial coordinate');
assert.doesNotMatch(ux,/IterionGame\.createGame\s*=|IterionEngine\.bestSignal\s*=|game\.finishPlacement\s*=function|game\.openShop\s*=function|game\.candidatesForIndex\s*=function/,'UX presentation layer must not own tutorial gameplay patches');
console.log('ux onboarding presentation regression OK');
