const assert=require('assert');
const fs=require('fs');
const path=require('path');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
assert.match(ui,/escapeHtml\(mod\.displayName\|\|mod\.name\)/,'Market UI must render offered modifier names from the registry');
assert.match(ui,/Add one random new physical domino to (?:this run|the current set)\./,'Shop must explain random physical tile supply');
assert.match(ui,/SUPPLY \$\{supply\} · \$\{nextMarket\}/,'Market must show physical tile supply and next Market timing');
assert.match(ui,/tileModMarks/,'Physical tile modifiers must have a visual marker renderer');
assert.match(ui,/function magnitude\(v\)/);
// Deliberate UI redesign: pacing/lifetime depend on activation count, not magnitude.
assert.match(ui,/V\.cascadeDelay\(index\)/);
assert.match(ui,/V\.effectLifetime\(index\)/);
assert.match(ui,/V\.CASCADE\.settleItemMs/);
assert.match(ui,/V\.cascadeSettlementPlan/);
assert.match(ui,/async function settleCascadeScore/);
assert.match(ui,/cascadeRetained cascadeOperation/,'Arithmetic operations must persist as cascade memory until settlement');
assert.match(ui,/V\.cascadeOperationKey\(laneId\(lane\),e\.piece,half,displayOperation\)/,'Repeated effects must group only by lane, physical piece, half and operation');
assert.match(ui,/el\.dataset\.repeatKey===repeatKey/,'Repeated operation lookup must reuse an existing anchored chip');
assert.match(ui,/updateOperationRepeat\(existing,\(Number\(existing\.dataset\.repeat\)\|\|1\)\+1\)/,'Repeated activations must increment the visual counter rather than add another chip');
assert.match(ui,/function operationsSettledWith\(/,'Score settlement must decide which retained operations disappear with each subtotal');
assert.match(ui,/ops\.forEach\(op=>op\.classList\.add\('cascadeToScore'\)\)/,'Operations must fade when their contribution enters Score');
assert.doesNotMatch(ui,/function finalFx\(/,'Central final-number renderer must stay removed');
assert.match(ui,/game\.finishPlacement\(ctx\);window\.NomonUiPolish\?\.snapScore\?\.\(game\.state\(\)\.score\)/,'Transient Score animation must hand back to authoritative game state after placement');
assert.match(ui,/reboundArrow/);
assert.match(ui,/Math\.atan2\(entry\.y-exit\.y,entry\.x-exit\.x\)/);
assert.doesNotMatch(html,/reboundGlyph/);
assert.match(html,/\.reboundArrow\{/);
assert.match(html,/\.tileModMark\{/);
assert.match(ui,/--mod-shift:\$\{\(i-\(marks\.length-1\)\/2\)\*5\}px/,'Any number of coexisting modifiers must remain centred and separated without becoming badges');
assert.match(ui,/<span>\$\{(?:label|mark\.label)\[0\]\}<\/span><span>\$\{(?:label|mark\.label)\[1\]\}<\/span>/,'Each modifier letter must occupy one physical half');
assert.match(html,/\.piece\.h>\.tileModMark\{grid-template-columns:1fr 1fr/,'Horizontal modifiers must read left to right');
assert.match(html,/\.piece\.v>\.tileModMark\{grid-template-rows:1fr 1fr/,'Vertical modifiers must read top to bottom');
assert.match(html,/background:transparent;color:rgba\(21,21,21,\.68\);font:900 8px/,'Modifier lettering must remain a bold direct print, not a badge');
assert.match(html,/<div class="boardTop">[^\n]*id="machineModStatus"/,'Long Chain status belongs above the board, not in the header');
assert.doesNotMatch(ui,/board\.style\.backgroundColor='#fff'/,'Board colour must remain theme-controlled in Endless');
assert.match(html,/animation:pop 1\.2s forwards/);
assert.match(html,/@keyframes dealIn\{[^}]*transform:scale\(\.88\)/,'Hand reveal must scale uniformly so dominoes never deform');
assert.doesNotMatch(html,/@keyframes dealIn\{[^\n]*scaleY/,'Hand reveal must never stretch the domino on one axis');
assert.doesNotMatch(html,/\.finalfx\{/,'Unused central final-number styling must stay removed');
console.log('retained v0.19 UI regression tests passed');
