const assert=require('assert');
const fs=require('fs');
const path=require('path');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
assert.match(ui,/escapeHtml\(mod\.displayName\|\|mod\.name\)/,'Market UI must render offered modifier names from the registry');
assert.match(ui,/Add one random new physical domino to this run\./,'Shop must explain random physical tile supply');
assert.match(ui,/SUPPLY \$\{supply\} · \$\{nextMarket\}/,'Market must show physical tile supply and next Market timing');
assert.match(ui,/tileModMarks/,'Physical tile modifiers must have a visual marker renderer');
assert.match(ui,/function magnitude\(v\)/);
// Deliberate UI redesign: pacing/lifetime depend on activation count, not magnitude.
assert.match(ui,/V\.cascadeDelay\(index\)/);
assert.match(ui,/V\.effectLifetime\(index\)/);
assert.match(ui,/V\.CASCADE\.finalMs/);
assert.match(ui,/reboundArrow/);
assert.match(ui,/Math\.atan2\(entry\.y-exit\.y,entry\.x-exit\.x\)/);
assert.doesNotMatch(html,/reboundGlyph/);
assert.match(html,/\.reboundArrow\{/);
assert.match(html,/\.tileModMark\{/);
assert.match(html,/animation:pop 1\.2s forwards/);
assert.match(html,/animation:final 1\.8s forwards/);
console.log('retained v0.19 UI regression tests passed');
