const assert=require('assert');
const fs=require('fs');
const path=require('path');
const data=fs.readFileSync(path.join(__dirname,'..','data.js'),'utf8');
const game=fs.readFileSync(path.join(__dirname,'..','game.js'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
assert.match(data,/VERSION:'0\.22\.0'/,'build must identify as v0.22.0');
assert.doesNotMatch(ui,/EXACT DOMINO/);
assert.doesNotMatch(ui,/exactGridHtml|buyMarketExactTile|marketExactPrice/);
assert.doesNotMatch(game,/buyMarketExactTile|marketExactPrice|MARKET_EXACT_TILE_COST/);
assert.match(ui,/Randomly upgrades one physical double you own\./);
assert.match(ui,/id="doubleDoubleBuy"/);
assert.match(ui,/ROLL DOUBLE DOUBLE/);
assert.doesNotMatch(ui,/data-dd-id|doubleDoubleGridHtml/);
assert.match(ui,/GAME\.buyDoubleDouble\(\)/);
assert.match(ui,/DOUBLE DOUBLE → \[\$\{r\.tile\.a\}\|\$\{r\.tile\.b\}\]/);
assert.match(ui,/SUPPLY \$\{supply\} · \$\{nextMarket\}/);
assert.match(game,/openingProtectionActive/);
assert.match(game,/type:'opening-protection'/);
assert.match(game,/ensureOpeningContinuation\('reroll'\)/);
console.log('v0.20 UI regression tests passed');
