const assert=require('assert');
const fs=require('fs');
const path=require('path');
const data=fs.readFileSync(path.join(__dirname,'..','data.js'),'utf8');
const game=fs.readFileSync(path.join(__dirname,'..','game.js'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
const mods=fs.readFileSync(path.join(__dirname,'..','mods.js'),'utf8');
assert.match(data,/VERSION:'0\.71\.1'/,'build must identify as the current release');
assert.doesNotMatch(ui,/EXACT DOMINO/);
assert.doesNotMatch(ui,/exactGridHtml|buyMarketExactTile|marketExactPrice/);
assert.doesNotMatch(game,/buyMarketExactTile|marketExactPrice|MARKET_EXACT_TILE_COST/);
assert.match(mods,/id:'double-double'/,'Double Double must remain registered');
assert.match(ui,/data-market-mod/,'Market must render generic modifier purchase controls');
assert.match(ui,/name=mod\.displayName\|\|mod\.name/,'Market must derive modifier display names from registry metadata');assert.match(ui,/class="marketOfferName">\$\{escapeHtml\(name\)\}/,'Market must render the registry name as the dominant card label');
assert.doesNotMatch(ui,/data-dd-id|doubleDoubleGridHtml/);
assert.match(ui,/GAME\.buyMarketMod\(id\)/,'Market UI must use the generic modifier purchase API');
assert.match(ui,/mod\.displayName\|\|mod\.name/,'Market result copy must use modifier metadata');
assert.match(ui,/class="marketOfferGrid\$\{pyramid\?' classicMarketPyramid':''\}"/,'Market must retain a compact offer decision surface while allowing the Classic pyramid layout');
assert.match(ui,/TAP A MOD = DETAILS · BUY ONE · INFLATION \+1/,'Market must expose the essential inspection, purchase and inflation rules without verbose prose');
assert.match(game,/openingProtectionActive/);
assert.match(game,/type:'opening-protection'/);
assert.match(game,/ensureOpeningContinuation\('reroll'\)/);
console.log('v0.20 UI regression tests passed');
