const assert=require('assert');
const fs=require('fs');
const path=require('path');
const game=fs.readFileSync(path.join(__dirname,'..','game.js'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
assert.doesNotMatch(ui,/EXACT DOMINO/);
assert.doesNotMatch(ui,/exactGridHtml|buyMarketExactTile|marketExactPrice/);
assert.doesNotMatch(game,/buyMarketExactTile|marketExactPrice|MARKET_EXACT_TILE_COST/);
assert.match(game,/openingProtectionActive/);
assert.match(game,/type:'opening-protection'/);
assert.match(game,/ensureOpeningContinuation\('reroll'\)/);
console.log('retained v0.20 UI regression tests passed');
