const assert=require('assert');
const fs=require('fs');
const path=require('path');
const data=fs.readFileSync(path.join(__dirname,'..','data.js'),'utf8');
const help=fs.readFileSync(path.join(__dirname,'..','help.js'),'utf8');
const gesture=fs.readFileSync(path.join(__dirname,'..','gesture.js'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
assert.match(data,/VERSION:'0\.28\.2'/);
assert.match(data,/LONG_PRESS_MS:500/);
assert.match(html,/id="helpButton"[^>]*>\?<\/button>/);
assert.match(html,/script src="help\.js"/);assert.match(html,/script src="gesture\.js"/);
assert.match(ui,/window\.IterionHelp/);assert.match(ui,/window\.IterionGesture/);assert.match(ui,/H\.inspectTile\(GAME\.state\(\),tileId\)/);
assert.match(help,/function tileRecord\(/);assert.match(help,/E\.applyOp\(value,isDouble,state,doubleDouble,powerMultiplier\)/);assert.doesNotMatch(ui,/E\.applyOp\(/);
assert.match(help,/help_open_count/);assert.match(help,/help_section_opened/);assert.match(ui,/fullDebugText\(\)/);
assert.match(ui,/b\.disabled=uiBusy/);assert.doesNotMatch(ui,/b\.disabled=!mask\[i\]\|\|uiBusy/);assert.match(ui,/onDragStart:\(meta,e\)=>\{if\(meta\.kind==='hand'\)startDrag/);assert.strictEqual((ui.match(/GAME\.beginPlacement/g)||[]).length,1);
assert.match(ui,/kind:'board',tileId:p\.tile\.id,allowDrag:false/);assert.match(html,/html,body\{[^}]*overflow:hidden/);assert.match(html,/\.app\{[^}]*overflow:hidden/);
assert.match(ui,/Best Score with this tile:/,'Inspector must show best Output for Moves involving the physical tile');
assert.match(ui,/can pay \+\$\{m\.starCoins\}c when activated/,'Inspector must show star coin income');
assert.doesNotMatch(ui,/Location: \$\{m\.location\}|Orientation: \$\{m\.axis\}|Connections: \$\{m\.connectionCount\}/,'Inspector must not expose tile position/orientation/connectivity');
const inspectorStart=ui.indexOf('function openTileInspector('),inspectorEnd=ui.indexOf('\n  function renderRulebook()',inspectorStart);assert(inspectorStart>=0&&inspectorEnd>inspectorStart);assert.doesNotMatch(ui.slice(inspectorStart,inspectorEnd),/beginPlacement|finishPlacement|bestSignal/);assert(gesture.includes("press.mode='inspect'"));
console.log('v0.21 UI regression tests passed');
