const assert=require('assert');
const fs=require('fs');
const path=require('path');
const read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const data=read('data.js'),game=read('game.js'),ui=read('ui.js'),html=read('index.html'),help=read('help.js');

assert.match(data,/VERSION:'0\.22\.1'/);
assert.match(data,/STAGE_SIZE:3/);
assert.match(data,/BOARD_SIZES:\[\[18,24\],\[21,28\],\[24,32\],\[27,36\],\[30,40\]\]/);
assert.doesNotMatch(data,/SHOP_CHANCE/,'inter-round random Shop chance must be removed');
assert.match(html,/id="shopButton"/,'gameplay rail must expose the always-available Shop');
assert.match(html,/id="stagestat">1\/5/,'HUD default must reflect five stages');
assert.match(html,/ROUND 1\/3/,'stage HUD default must reflect three rounds');
assert.match(html,/html,body\{[^}]*overflow:hidden/,'full-screen no-scroll gameplay must be preserved');
assert.match(html,/class="handRail"/,'hand must remain on the right rail');
assert.match(game,/function canOpenShop\(/);
assert.match(game,/function openShop\(/);
assert.match(game,/function buyShopRandomTile\(/);
assert.match(game,/s\.nextShopType=endOfStage\?'market':'none'/,'only Markets should be scheduled between rounds');
assert.doesNotMatch(game,/buyMarketRandomTile/,'random tile supply must not remain a Market API');
assert.match(ui,/GAME\.buyShopRandomTile\(\)/);
assert.match(ui,/GAME\.buyShopItem\(id\)/);
assert.match(ui,/overlayTitle\.textContent='MARKET'/);
const marketStart=ui.indexOf('function showMarket()'),marketEnd=ui.indexOf('\n  function showNoMoves()',marketStart);
assert(marketStart>=0&&marketEnd>marketStart);
assert.doesNotMatch(ui.slice(marketStart,marketEnd),/MYSTERY DOMINO|buyShopRandomTile/,'Market UI must not sell basic random tile supply');
assert.match(help,/id:'economy',displayName:'Shop \/ Market'/,'Rulebook must explain the Shop / Market split');
assert.match(help,/SHOP anytime/);
console.log('v0.22 UI regression tests passed');
