const assert=require('assert');
const fs=require('fs');
const path=require('path');
const D=require('../data.js');
const E=require('../engine.js');
const G=require('../game.js');

assert.strictEqual(D.VERSION,'0.38.0');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'..','ui.js'),'utf8');
assert.match(html,/id="titleCard"[^>]*role="button"[^>]*tabindex="0"/);
assert.match(html,/LEARN BASICS · 2 MIN/);
assert.match(html,/SYSTEMS TUTORIAL · 3 MIN/);
assert.match(html,/SKIP · START RUN/);
assert.match(html,/id="continueRun"/);
assert.match(html,/id="replayTutorial"/);
assert.match(html,/id="systemsTutorial"/);
assert.match(html,/class="selectionDouble"/);
assert.match(ui,/e\.stopPropagation\(\);showSelection\(\)/,'entry activation must consume the event');
assert.match(fs.readFileSync(path.join(__dirname,'..','ui-theme.css'),'utf8'),/\.entryScreen\[hidden\],\.firstRunChoice\[hidden\],\.gameSelection>\[hidden\]\{display:none!important\}/,'grid entry screens must honor hidden');
assert.match(ui,/\$\('startRun'\)\.textContent=saved\?'NEW RUN'/,'new run must remain separate from continue');
assert.match(ui,/confirm\('Replace the saved run with a new run\?'\)/,'replacing a saved run requires confirmation');
assert.match(ui,/if\(tutorial\)return GAME\.snapshot\(\)/,'tutorial must never write normal-run storage');
assert.match(ui,/if\(!tutorial\)activeRun=GAME/,'retry must retain the original normal-run reference');
assert.match(ui,/const game=GAME/,'an asynchronous placement must retain its owning game instance');
assert.match(ui,/tutorial\.exitPending=true/,'exit during an asynchronous tutorial action must be deferred');
assert.match(ui,/if\(exitPending\)\{leaveTutorial\(false\);return\}/);
assert.match(ui,/shopBtn\.disabled=!!tutorial/);assert.match(ui,/rerollBtn\.disabled=!!tutorial/);assert.match(ui,/menuButton\.disabled=!!tutorial/);
assert.match(ui,/GAME\.openShop\(\)/,'the final Basics tutorial step must open the real Shop state');
assert.match(ui,/tutorial\?\.step===5/);assert.match(ui,/Market appears only between stages/);
assert.match(ui,/if\(!tutorial&&\(game\.state\(\)\.cleared\|\|game\.state\(\)\.blocked\)\)armOutcomeDelay/,'normal outcome timing must not replace tutorial completion');

const normal=G.createGame(E,{seed:3101});
const before=normal.exportState();
const tutorial=G.createGame(E,{seed:3100,TARGETS:[1e9],STARTING_COINS:30});
assert.notStrictEqual(normal.state().runId,tutorial.state().runId);
assert.notStrictEqual(normal.state().rngState,tutorial.state().rngState);
assert.deepStrictEqual(normal.exportState(),before,'creating and playing a tutorial sandbox must not mutate the normal run');

const restored=G.createGame(E,{seed:9});
assert.strictEqual(restored.restoreState(before),true);
assert.deepStrictEqual(restored.exportState(),before,'active run state and RNG must round-trip exactly');
assert.strictEqual(restored.state().hand[0].a,restored.state().hand[0].b,'continued opening hand retains the real first-double rule');
assert.strictEqual(restored.beginPlacement(1,{x:0,y:0,rr:0}).reason,'first-double','normal run opening rules remain authoritative');
assert.strictEqual(restored.restoreState({schema:'wrong'}),false);
console.log('v0.31 entry, persistence and tutorial isolation regression tests passed');
