const fs=require('fs');
function replace(path,from,to,label){let src=fs.readFileSync(path,'utf8');if(!src.includes(from))throw new Error(`${label} baseline mismatch`);src=src.replace(from,to);fs.writeFileSync(path,src)}

replace('data.js',`    MARKET_LONG_RUN_COST:8,\n    LONG_RUN_UNIQUE_THRESHOLD:10,`,`    MARKET_LONG_RUN_COST:8,\n    MARKET_ZERO_MEMORY_COST:9,\n    LONG_RUN_UNIQUE_THRESHOLD:10,`,'Stage C data');

replace('mods.js',`  register({id:'long-run',displayName:'LONG RUN',name:'LONG RUN',kind:'market-machine-mod',market:true,target:'machine',marketCostKey:'MARKET_LONG_RUN_COST',shortDescription:'Long routes pay every activated star once.',rulesDescription:'When the chosen route traverses at least 10 unique physical tiles in one Move, every starred physical tile activated on that route pays its tier once. Otherwise the normal highest-star-wins rule remains.',description:'At 10+ unique routed tiles, all activated stars pay once instead of only the highest tier.'});\n  return{register,get,all};`,`  register({id:'long-run',displayName:'LONG RUN',name:'LONG RUN',kind:'market-machine-mod',market:true,target:'machine',marketCostKey:'MARKET_LONG_RUN_COST',shortDescription:'Long routes pay every activated star once.',rulesDescription:'When the chosen route traverses at least 10 unique physical tiles in one Move, every starred physical tile activated on that route pays its tier once. Otherwise the normal highest-star-wins rule remains.',description:'At 10+ unique routed tiles, all activated stars pay once instead of only the highest tier.'});\n  register({id:'zero-memory',displayName:'ZERO MEMORY',name:'ZERO MEMORY',kind:'market-tile-mod',market:true,target:'zero',marketCostKey:'MARKET_ZERO_MEMORY_COST',shortDescription:'A placed zero remembers the previous scoring operation.',rulesDescription:'On this physical zero tile’s first rebound each Move, repeat exactly once the immediately preceding non-zero scoring operation, then continue the normal rebound. Zero charges and routing are unchanged.',description:'On its first rebound each Move, repeat the previous non-zero scoring operation once.'});\n  return{register,get,all};`,'Stage C mods');

replace('engine.js',`  function better(a,b){if(!b)return true;const av=[a.traversals||0,a.output||0,a.rebounds||0,(a.path||[]).length],bv=[b.traversals||0,b.output||0,b.rebounds||0,(b.path||[]).length];for(let i=0;i<av.length;i++){if(av[i]!==bv[i])return av[i]>bv[i]}return false}\n  function bestSignal(newPieceId,pieces,opts={}){`,`  function better(a,b){if(!b)return true;const av=[a.traversals||0,a.output||0,a.rebounds||0,(a.path||[]).length],bv=[b.traversals||0,b.output||0,b.rebounds||0,(b.path||[]).length];for(let i=0;i<av.length;i++){if(av[i]!==bv[i])return av[i]>bv[i]}return false}\n  function replaySelectedScoring(result,initialOutput,opts={}){\n    if(!opts.zeroMemoryPieceId)return result;\n    let output=initialOutput,lastNonZero=null,pendingZero=null,zeroMemoryUsed=false;const events=[];\n    for(const raw of result.events||[]){\n      if(raw.type==='op'){\n        const e={...raw,before:output};\n        if(e.op==='multiply'){e.after=output*(e.factor||1);e.delta=e.after-output;output=e.after;lastNonZero={piece:e.piece,value:e.value,op:e.op,factor:e.factor||1,add:0,doubleDouble:!!e.doubleDouble}}\n        else if(e.op==='add'){e.after=output+(e.add||0);e.delta=e.after-output;output=e.after;lastNonZero={piece:e.piece,value:e.value,op:e.op,factor:0,add:e.add||0,doubleDouble:!!e.doubleDouble}}\n        else{e.after=output;e.delta=0}\n        pendingZero=e.op==='zero'?e.piece:null;events.push(e);continue\n      }\n      if(raw.type==='rebound'){\n        if(!zeroMemoryUsed&&raw.piece===opts.zeroMemoryPieceId&&pendingZero===raw.piece&&lastNonZero){\n          const before=output,after=lastNonZero.op==='multiply'?before*lastNonZero.factor:before+lastNonZero.add;\n          events.push({type:'zero-memory',piece:raw.piece,sourcePiece:lastNonZero.piece,sourceValue:lastNonZero.value,op:lastNonZero.op,factor:lastNonZero.factor||0,add:lastNonZero.add||0,doubleDouble:!!lastNonZero.doubleDouble,before,after,delta:after-before});\n          output=after;zeroMemoryUsed=true\n        }\n        events.push({...raw});pendingZero=null;continue\n      }\n      events.push({...raw});if(raw.type==='zero-pass'||raw.type==='die')pendingZero=null\n    }\n    return{...result,output,gain:output-initialOutput,events,zeroMemoryActivated:zeroMemoryUsed}\n  }\n  function bestSignal(newPieceId,pieces,opts={}){`,'Stage C engine replay helper');

replace('engine.js',`    best=best||{output:initialOutput,gain:0,path:[],segments:[],events:[],reason:'no-route',traversals:0,rebounds:0};best.search={starts:starts.length,expanded,leaves,truncated};return best\n  }`,`    best=best||{output:initialOutput,gain:0,path:[],segments:[],events:[],reason:'no-route',traversals:0,rebounds:0};best.search={starts:starts.length,expanded,leaves,truncated};return replaySelectedScoring(best,initialOutput,opts)\n  }`,'Stage C post-selection application');

replace('engine.js',`  const api={S,DIR,ARROW,axis,setBoardSize,getBoardSize,cubesFor,rectForCubes,pieceFrom,edgeContact,contactBetweenPieces,validatePlacement,allPlacements,hasAnyPlacement,hasLegalMove,cubeCenter,connectionsForPiece,connectionKey,startChoices,applyOp,bestSignal,simulateSignal,exposedPorts};`,`  const api={S,DIR,ARROW,axis,setBoardSize,getBoardSize,cubesFor,rectForCubes,pieceFrom,edgeContact,contactBetweenPieces,validatePlacement,allPlacements,hasAnyPlacement,hasLegalMove,cubeCenter,connectionsForPiece,connectionKey,startChoices,applyOp,replaySelectedScoring,bestSignal,simulateSignal,exposedPorts};`,'Stage C engine API');

replace('game.js',`tileSerial:0,boardStage:0,doubleDoubleTileId:null};`,`tileSerial:0,boardStage:0,doubleDoubleTileId:null,zeroMemoryTileId:null};`,'Stage C state');

replace('game.js',`    const doubleDoublePieceId=s.pieces.find(x=>x.tile.id===s.doubleDoubleTileId)?.id||null;\n    const sim=s.pieces.length===1?{output:trigger,events:[],reason:'root',rebounds:0,search:{starts:0,leaves:1,expanded:0}}:E.bestSignal(p.id,s.pieces,{initialOutput:trigger,doubleDoublePieceId});`,`    const doubleDoublePieceId=s.pieces.find(x=>x.tile.id===s.doubleDoubleTileId)?.id||null,zeroMemoryPieceId=s.pieces.find(x=>x.tile.id===s.zeroMemoryTileId)?.id||null;\n    const sim=s.pieces.length===1?{output:trigger,events:[],reason:'root',rebounds:0,search:{starts:0,leaves:1,expanded:0}}:E.bestSignal(p.id,s.pieces,{initialOutput:trigger,doubleDoublePieceId,zeroMemoryPieceId});`,'Stage C game engine opts');

replace('game.js',`    if(m.target==='double')return placed.filter(t=>isDouble(t)&&t.a>0&&(id!=='double-double'||t.id!==s.doubleDoubleTileId));\n    return[]`,`    if(m.target==='double')return placed.filter(t=>isDouble(t)&&t.a>0&&(id!=='double-double'||t.id!==s.doubleDoubleTileId));\n    if(m.target==='zero')return placed.filter(t=>isZero(t)&&(id!=='zero-memory'||t.id!==s.zeroMemoryTileId));\n    return[]`,'Stage C zero targets');

replace('game.js',`    let tile=null,previousTileId=null,candidateCount=1;\n    if(m.target==='double'){const candidates=marketTargetTiles(id);candidateCount=candidates.length;tile=candidates[Math.floor(rnd()*candidates.length)];previousTileId=id==='double-double'?(s.doubleDoubleTileId||null):null}\n    if(id!=='double-double'&&id!=='long-run')return{ok:false,reason:'unsupported'};\n    const purchase=applyPurchase(cost);\n    if(id==='double-double')s.doubleDoubleTileId=tile.id;\n    if(id==='long-run'&&!s.mods.includes(id))s.mods.push(id);`,`    let tile=null,previousTileId=null,candidateCount=1;\n    if(m.target==='double'||m.target==='zero'){const candidates=marketTargetTiles(id);candidateCount=candidates.length;tile=candidates[Math.floor(rnd()*candidates.length)];previousTileId=id==='double-double'?(s.doubleDoubleTileId||null):id==='zero-memory'?(s.zeroMemoryTileId||null):null}\n    if(id!=='double-double'&&id!=='long-run'&&id!=='zero-memory')return{ok:false,reason:'unsupported'};\n    const purchase=applyPurchase(cost);\n    if(id==='double-double')s.doubleDoubleTileId=tile.id;\n    if(id==='zero-memory')s.zeroMemoryTileId=tile.id;\n    if(id==='long-run'&&!s.mods.includes(id))s.mods.push(id);`,'Stage C market purchase support');

const engineTest=`const assert=require('assert');\nconst fs=require('fs');\nconst E=require('../engine.js');\n\nE.setBoardSize(18,24);\nconst entry=E.pieceFrom({a:1,b:5},0,0,0,0,3);entry.tile={id:'entry',a:1,b:5};\nconst mid=E.pieceFrom({a:5,b:5},4,0,0,0,1);mid.tile={id:'mid',a:5,b:5};\nconst zero=E.pieceFrom({a:5,b:0},8,0,0,0,2);zero.tile={id:'zero',a:5,b:0};\nconst pieces=[entry,mid,zero];\nconst normal=E.bestSignal(entry.id,pieces,{initialOutput:6});\nconst memory=E.bestSignal(entry.id,pieces,{initialOutput:6,zeroMemoryPieceId:zero.id});\nassert.strictEqual(normal.output,750,'fixture retains canonical rebound output');\nassert.strictEqual(memory.output,3750,'Zero Memory repeats the immediately previous ×5 once');\nassert.strictEqual(memory.rebounds,normal.rebounds,'Zero Memory must not change rebound count or charges');\nassert.deepStrictEqual(memory.path,normal.path,'Zero Memory must not change the selected route path');\nassert.deepStrictEqual(memory.segments,normal.segments,'Zero Memory must not change selected route segments');\nconst zm=memory.events.filter(e=>e.type==='zero-memory');\nassert.strictEqual(zm.length,1,'Zero Memory activates at most once per Move');\nassert.strictEqual(zm[0].op,'multiply');assert.strictEqual(zm[0].factor,5);\nconst zeroOpIndex=memory.events.findIndex(e=>e.type==='op'&&e.piece===zero.id&&e.op==='zero'),memoryIndex=memory.events.findIndex(e=>e.type==='zero-memory'),reboundIndex=memory.events.findIndex(e=>e.type==='rebound'&&e.piece===zero.id);\nassert(zeroOpIndex<memoryIndex&&memoryIndex<reboundIndex,'event order must be scoring op → ZERO → repeated op → rebound');\nconst source=fs.readFileSync(require.resolve('../engine.js'),'utf8');\nassert(source.includes('const av=[a.traversals||0,a.output||0,a.rebounds||0,(a.path||[]).length]'),'route comparator must remain traversals → output → rebounds → path length');\nconsole.log('v0.23 Stage C Zero Memory isolated engine tests passed');\n`;
fs.writeFileSync('tests/v023-stage-c-engine.test.js',engineTest);

const gameTest=`const assert=require('assert');\nconst D=require('../data.js');const E=require('../engine.js');const Game=require('../game.js');\nassert.strictEqual(D.VERSION,'0.22.1');assert.strictEqual(D.MARKET_ZERO_MEMORY_COST,9);\nE.setBoardSize(18,24);const game=Game.createGame(E,{seed:2303,STARTING_COINS:100}),s=game.state(),by=id=>s.set.find(t=>t.id===id);\nconst placed=by('d0-5'),reserveZero=by('d0-6');function piece(t,x,id){const p=E.pieceFrom(t,x,0,0,0,id);p.tile={...t};return p}\ns.pieces=[piece(placed,0,1)];s.placedTileIds=[placed.id];s.hand=[reserveZero,null,null,null,null];s.reserve=s.set.filter(t=>t.id!==reserveZero.id&&!s.placedTileIds.includes(t.id));s.cleared=true;s.round=2;s.nextShopType='market';s.intermissionResolved=false;s.coins=100;s.inflation=1;\nassert.strictEqual(game.openIntermission(),true);assert(s.shopOffers.includes('zero-memory'));assert.strictEqual(game.marketTargetCount('zero-memory'),1,'only placed zero is eligible');\nconst buy=game.buyMarketMod('zero-memory');assert.strictEqual(buy.ok,true);assert.strictEqual(buy.tile.id,placed.id);assert.strictEqual(buy.cost,10);assert.strictEqual(s.zeroMemoryTileId,placed.id);assert.strictEqual(s.inflation,2);\nassert.strictEqual(game.buyMarketMod('long-run').reason,'limit','one Market purchase limit still applies');\nconsole.log('v0.23 Stage C Zero Memory Market tests passed');\n`;
fs.writeFileSync('tests/v023-stage-c-game.test.js',gameTest);fs.unlinkSync(__filename);
